// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminAPIKeysColumns holds the columns for the "admin_api_keys" table.
	AdminAPIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "key_hash", Type: field.TypeString, Unique: true},
		{Name: "key_prefix", Type: field.TypeString, Size: 8},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AdminAPIKeysTable holds the schema information for the "admin_api_keys" table.
	AdminAPIKeysTable = &schema.Table{
		Name:       "admin_api_keys",
		Columns:    AdminAPIKeysColumns,
		PrimaryKey: []*schema.Column{AdminAPIKeysColumns[0]},
	}
	// BooksColumns holds the columns for the "books" table.
	BooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "book_title", Type: field.TypeString},
		{Name: "author", Type: field.TypeString},
		{Name: "book_isbn", Type: field.TypeString, Nullable: true},
		{Name: "thumbnail_url", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_books", Type: field.TypeUUID},
	}
	// BooksTable holds the schema information for the "books" table.
	BooksTable = &schema.Table{
		Name:       "books",
		Columns:    BooksColumns,
		PrimaryKey: []*schema.Column{BooksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "books_users_books",
				Columns:    []*schema.Column{BooksColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// BookmarksColumns holds the columns for the "bookmarks" table.
	BookmarksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "book_bookmarks", Type: field.TypeUUID},
		{Name: "user_bookmarks", Type: field.TypeUUID},
	}
	// BookmarksTable holds the schema information for the "bookmarks" table.
	BookmarksTable = &schema.Table{
		Name:       "bookmarks",
		Columns:    BookmarksColumns,
		PrimaryKey: []*schema.Column{BookmarksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bookmarks_books_bookmarks",
				Columns:    []*schema.Column{BookmarksColumns[2]},
				RefColumns: []*schema.Column{BooksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "bookmarks_users_bookmarks",
				Columns:    []*schema.Column{BookmarksColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// EmailVerificationsColumns holds the columns for the "email_verifications" table.
	EmailVerificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString},
		{Name: "code", Type: field.TypeString, Size: 6},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "is_verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// EmailVerificationsTable holds the schema information for the "email_verifications" table.
	EmailVerificationsTable = &schema.Table{
		Name:       "email_verifications",
		Columns:    EmailVerificationsColumns,
		PrimaryKey: []*schema.Column{EmailVerificationsColumns[0]},
	}
	// ReadingRemindersColumns holds the columns for the "reading_reminders" table.
	ReadingRemindersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "reminder_time", Type: field.TypeString},
		{Name: "day_of_week", Type: field.TypeEnum, Enums: []string{"everyday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"}, Default: "everyday"},
		{Name: "is_enabled", Type: field.TypeBool, Default: true},
		{Name: "message", Type: field.TypeString, Default: "책 읽을 시간이에요!"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_reading_reminders", Type: field.TypeUUID},
	}
	// ReadingRemindersTable holds the schema information for the "reading_reminders" table.
	ReadingRemindersTable = &schema.Table{
		Name:       "reading_reminders",
		Columns:    ReadingRemindersColumns,
		PrimaryKey: []*schema.Column{ReadingRemindersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "reading_reminders_users_reading_reminders",
				Columns:    []*schema.Column{ReadingRemindersColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ReviewsColumns holds the columns for the "reviews" table.
	ReviewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "rating", Type: field.TypeInt},
		{Name: "is_public", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "book_reviews", Type: field.TypeUUID},
		{Name: "user_reviews", Type: field.TypeUUID},
	}
	// ReviewsTable holds the schema information for the "reviews" table.
	ReviewsTable = &schema.Table{
		Name:       "reviews",
		Columns:    ReviewsColumns,
		PrimaryKey: []*schema.Column{ReviewsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "reviews_books_reviews",
				Columns:    []*schema.Column{ReviewsColumns[6]},
				RefColumns: []*schema.Column{BooksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "reviews_users_reviews",
				Columns:    []*schema.Column{ReviewsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "nick_name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString, Nullable: true},
		{Name: "is_published", Type: field.TypeBool, Default: false},
		{Name: "is_terms_agreed", Type: field.TypeBool, Default: false},
		{Name: "fcm_token", Type: field.TypeString, Nullable: true},
		{Name: "timezone", Type: field.TypeString, Default: "Asia/Seoul"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminAPIKeysTable,
		BooksTable,
		BookmarksTable,
		EmailVerificationsTable,
		ReadingRemindersTable,
		ReviewsTable,
		UsersTable,
	}
)

func init() {
	BooksTable.ForeignKeys[0].RefTable = UsersTable
	BookmarksTable.ForeignKeys[0].RefTable = BooksTable
	BookmarksTable.ForeignKeys[1].RefTable = UsersTable
	ReadingRemindersTable.ForeignKeys[0].RefTable = UsersTable
	ReviewsTable.ForeignKeys[0].RefTable = BooksTable
	ReviewsTable.ForeignKeys[1].RefTable = UsersTable
}
