// Code generated by ent, DO NOT EDIT.

package adminapikey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldName, v))
}

// KeyHash applies equality check predicate on the "key_hash" field. It's identical to KeyHashEQ.
func KeyHash(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldKeyHash, v))
}

// KeyPrefix applies equality check predicate on the "key_prefix" field. It's identical to KeyPrefixEQ.
func KeyPrefix(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldKeyPrefix, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldIsActive, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldContainsFold(FieldName, v))
}

// KeyHashEQ applies the EQ predicate on the "key_hash" field.
func KeyHashEQ(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldKeyHash, v))
}

// KeyHashNEQ applies the NEQ predicate on the "key_hash" field.
func KeyHashNEQ(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNEQ(FieldKeyHash, v))
}

// KeyHashIn applies the In predicate on the "key_hash" field.
func KeyHashIn(vs ...string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldIn(FieldKeyHash, vs...))
}

// KeyHashNotIn applies the NotIn predicate on the "key_hash" field.
func KeyHashNotIn(vs ...string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNotIn(FieldKeyHash, vs...))
}

// KeyHashGT applies the GT predicate on the "key_hash" field.
func KeyHashGT(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGT(FieldKeyHash, v))
}

// KeyHashGTE applies the GTE predicate on the "key_hash" field.
func KeyHashGTE(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGTE(FieldKeyHash, v))
}

// KeyHashLT applies the LT predicate on the "key_hash" field.
func KeyHashLT(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLT(FieldKeyHash, v))
}

// KeyHashLTE applies the LTE predicate on the "key_hash" field.
func KeyHashLTE(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLTE(FieldKeyHash, v))
}

// KeyHashContains applies the Contains predicate on the "key_hash" field.
func KeyHashContains(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldContains(FieldKeyHash, v))
}

// KeyHashHasPrefix applies the HasPrefix predicate on the "key_hash" field.
func KeyHashHasPrefix(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldHasPrefix(FieldKeyHash, v))
}

// KeyHashHasSuffix applies the HasSuffix predicate on the "key_hash" field.
func KeyHashHasSuffix(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldHasSuffix(FieldKeyHash, v))
}

// KeyHashEqualFold applies the EqualFold predicate on the "key_hash" field.
func KeyHashEqualFold(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEqualFold(FieldKeyHash, v))
}

// KeyHashContainsFold applies the ContainsFold predicate on the "key_hash" field.
func KeyHashContainsFold(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldContainsFold(FieldKeyHash, v))
}

// KeyPrefixEQ applies the EQ predicate on the "key_prefix" field.
func KeyPrefixEQ(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldKeyPrefix, v))
}

// KeyPrefixNEQ applies the NEQ predicate on the "key_prefix" field.
func KeyPrefixNEQ(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNEQ(FieldKeyPrefix, v))
}

// KeyPrefixIn applies the In predicate on the "key_prefix" field.
func KeyPrefixIn(vs ...string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldIn(FieldKeyPrefix, vs...))
}

// KeyPrefixNotIn applies the NotIn predicate on the "key_prefix" field.
func KeyPrefixNotIn(vs ...string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNotIn(FieldKeyPrefix, vs...))
}

// KeyPrefixGT applies the GT predicate on the "key_prefix" field.
func KeyPrefixGT(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGT(FieldKeyPrefix, v))
}

// KeyPrefixGTE applies the GTE predicate on the "key_prefix" field.
func KeyPrefixGTE(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGTE(FieldKeyPrefix, v))
}

// KeyPrefixLT applies the LT predicate on the "key_prefix" field.
func KeyPrefixLT(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLT(FieldKeyPrefix, v))
}

// KeyPrefixLTE applies the LTE predicate on the "key_prefix" field.
func KeyPrefixLTE(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLTE(FieldKeyPrefix, v))
}

// KeyPrefixContains applies the Contains predicate on the "key_prefix" field.
func KeyPrefixContains(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldContains(FieldKeyPrefix, v))
}

// KeyPrefixHasPrefix applies the HasPrefix predicate on the "key_prefix" field.
func KeyPrefixHasPrefix(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldHasPrefix(FieldKeyPrefix, v))
}

// KeyPrefixHasSuffix applies the HasSuffix predicate on the "key_prefix" field.
func KeyPrefixHasSuffix(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldHasSuffix(FieldKeyPrefix, v))
}

// KeyPrefixEqualFold applies the EqualFold predicate on the "key_prefix" field.
func KeyPrefixEqualFold(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEqualFold(FieldKeyPrefix, v))
}

// KeyPrefixContainsFold applies the ContainsFold predicate on the "key_prefix" field.
func KeyPrefixContainsFold(v string) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldContainsFold(FieldKeyPrefix, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNEQ(FieldIsActive, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNotNull(FieldLastUsedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNotNull(FieldExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminAPIKey) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminAPIKey) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminAPIKey) predicate.AdminAPIKey {
	return predicate.AdminAPIKey(sql.NotPredicates(p))
}
