// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/adminapikey"
	"github.com/google/uuid"
)

// AdminAPIKeyCreate is the builder for creating a AdminAPIKey entity.
type AdminAPIKeyCreate struct {
	config
	mutation *AdminAPIKeyMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (aakc *AdminAPIKeyCreate) SetName(s string) *AdminAPIKeyCreate {
	aakc.mutation.SetName(s)
	return aakc
}

// SetKeyHash sets the "key_hash" field.
func (aakc *AdminAPIKeyCreate) SetKeyHash(s string) *AdminAPIKeyCreate {
	aakc.mutation.SetKeyHash(s)
	return aakc
}

// SetKeyPrefix sets the "key_prefix" field.
func (aakc *AdminAPIKeyCreate) SetKeyPrefix(s string) *AdminAPIKeyCreate {
	aakc.mutation.SetKeyPrefix(s)
	return aakc
}

// SetIsActive sets the "is_active" field.
func (aakc *AdminAPIKeyCreate) SetIsActive(b bool) *AdminAPIKeyCreate {
	aakc.mutation.SetIsActive(b)
	return aakc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (aakc *AdminAPIKeyCreate) SetNillableIsActive(b *bool) *AdminAPIKeyCreate {
	if b != nil {
		aakc.SetIsActive(*b)
	}
	return aakc
}

// SetLastUsedAt sets the "last_used_at" field.
func (aakc *AdminAPIKeyCreate) SetLastUsedAt(t time.Time) *AdminAPIKeyCreate {
	aakc.mutation.SetLastUsedAt(t)
	return aakc
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (aakc *AdminAPIKeyCreate) SetNillableLastUsedAt(t *time.Time) *AdminAPIKeyCreate {
	if t != nil {
		aakc.SetLastUsedAt(*t)
	}
	return aakc
}

// SetExpiresAt sets the "expires_at" field.
func (aakc *AdminAPIKeyCreate) SetExpiresAt(t time.Time) *AdminAPIKeyCreate {
	aakc.mutation.SetExpiresAt(t)
	return aakc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (aakc *AdminAPIKeyCreate) SetNillableExpiresAt(t *time.Time) *AdminAPIKeyCreate {
	if t != nil {
		aakc.SetExpiresAt(*t)
	}
	return aakc
}

// SetCreatedAt sets the "created_at" field.
func (aakc *AdminAPIKeyCreate) SetCreatedAt(t time.Time) *AdminAPIKeyCreate {
	aakc.mutation.SetCreatedAt(t)
	return aakc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aakc *AdminAPIKeyCreate) SetNillableCreatedAt(t *time.Time) *AdminAPIKeyCreate {
	if t != nil {
		aakc.SetCreatedAt(*t)
	}
	return aakc
}

// SetUpdatedAt sets the "updated_at" field.
func (aakc *AdminAPIKeyCreate) SetUpdatedAt(t time.Time) *AdminAPIKeyCreate {
	aakc.mutation.SetUpdatedAt(t)
	return aakc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (aakc *AdminAPIKeyCreate) SetNillableUpdatedAt(t *time.Time) *AdminAPIKeyCreate {
	if t != nil {
		aakc.SetUpdatedAt(*t)
	}
	return aakc
}

// SetID sets the "id" field.
func (aakc *AdminAPIKeyCreate) SetID(u uuid.UUID) *AdminAPIKeyCreate {
	aakc.mutation.SetID(u)
	return aakc
}

// Mutation returns the AdminAPIKeyMutation object of the builder.
func (aakc *AdminAPIKeyCreate) Mutation() *AdminAPIKeyMutation {
	return aakc.mutation
}

// Save creates the AdminAPIKey in the database.
func (aakc *AdminAPIKeyCreate) Save(ctx context.Context) (*AdminAPIKey, error) {
	aakc.defaults()
	return withHooks(ctx, aakc.sqlSave, aakc.mutation, aakc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (aakc *AdminAPIKeyCreate) SaveX(ctx context.Context) *AdminAPIKey {
	v, err := aakc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aakc *AdminAPIKeyCreate) Exec(ctx context.Context) error {
	_, err := aakc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aakc *AdminAPIKeyCreate) ExecX(ctx context.Context) {
	if err := aakc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aakc *AdminAPIKeyCreate) defaults() {
	if _, ok := aakc.mutation.IsActive(); !ok {
		v := adminapikey.DefaultIsActive
		aakc.mutation.SetIsActive(v)
	}
	if _, ok := aakc.mutation.CreatedAt(); !ok {
		v := adminapikey.DefaultCreatedAt()
		aakc.mutation.SetCreatedAt(v)
	}
	if _, ok := aakc.mutation.UpdatedAt(); !ok {
		v := adminapikey.DefaultUpdatedAt()
		aakc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aakc *AdminAPIKeyCreate) check() error {
	if _, ok := aakc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AdminAPIKey.name"`)}
	}
	if v, ok := aakc.mutation.Name(); ok {
		if err := adminapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminAPIKey.name": %w`, err)}
		}
	}
	if _, ok := aakc.mutation.KeyHash(); !ok {
		return &ValidationError{Name: "key_hash", err: errors.New(`ent: missing required field "AdminAPIKey.key_hash"`)}
	}
	if v, ok := aakc.mutation.KeyHash(); ok {
		if err := adminapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "AdminAPIKey.key_hash": %w`, err)}
		}
	}
	if _, ok := aakc.mutation.KeyPrefix(); !ok {
		return &ValidationError{Name: "key_prefix", err: errors.New(`ent: missing required field "AdminAPIKey.key_prefix"`)}
	}
	if v, ok := aakc.mutation.KeyPrefix(); ok {
		if err := adminapikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "AdminAPIKey.key_prefix": %w`, err)}
		}
	}
	if _, ok := aakc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "AdminAPIKey.is_active"`)}
	}
	if _, ok := aakc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminAPIKey.created_at"`)}
	}
	if _, ok := aakc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdminAPIKey.updated_at"`)}
	}
	return nil
}

func (aakc *AdminAPIKeyCreate) sqlSave(ctx context.Context) (*AdminAPIKey, error) {
	if err := aakc.check(); err != nil {
		return nil, err
	}
	_node, _spec := aakc.createSpec()
	if err := sqlgraph.CreateNode(ctx, aakc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	aakc.mutation.id = &_node.ID
	aakc.mutation.done = true
	return _node, nil
}

func (aakc *AdminAPIKeyCreate) createSpec() (*AdminAPIKey, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminAPIKey{config: aakc.config}
		_spec = sqlgraph.NewCreateSpec(adminapikey.Table, sqlgraph.NewFieldSpec(adminapikey.FieldID, field.TypeUUID))
	)
	if id, ok := aakc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := aakc.mutation.Name(); ok {
		_spec.SetField(adminapikey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := aakc.mutation.KeyHash(); ok {
		_spec.SetField(adminapikey.FieldKeyHash, field.TypeString, value)
		_node.KeyHash = value
	}
	if value, ok := aakc.mutation.KeyPrefix(); ok {
		_spec.SetField(adminapikey.FieldKeyPrefix, field.TypeString, value)
		_node.KeyPrefix = value
	}
	if value, ok := aakc.mutation.IsActive(); ok {
		_spec.SetField(adminapikey.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := aakc.mutation.LastUsedAt(); ok {
		_spec.SetField(adminapikey.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := aakc.mutation.ExpiresAt(); ok {
		_spec.SetField(adminapikey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := aakc.mutation.CreatedAt(); ok {
		_spec.SetField(adminapikey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := aakc.mutation.UpdatedAt(); ok {
		_spec.SetField(adminapikey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AdminAPIKeyCreateBulk is the builder for creating many AdminAPIKey entities in bulk.
type AdminAPIKeyCreateBulk struct {
	config
	err      error
	builders []*AdminAPIKeyCreate
}

// Save creates the AdminAPIKey entities in the database.
func (aakcb *AdminAPIKeyCreateBulk) Save(ctx context.Context) ([]*AdminAPIKey, error) {
	if aakcb.err != nil {
		return nil, aakcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(aakcb.builders))
	nodes := make([]*AdminAPIKey, len(aakcb.builders))
	mutators := make([]Mutator, len(aakcb.builders))
	for i := range aakcb.builders {
		func(i int, root context.Context) {
			builder := aakcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminAPIKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aakcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aakcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aakcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aakcb *AdminAPIKeyCreateBulk) SaveX(ctx context.Context) []*AdminAPIKey {
	v, err := aakcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aakcb *AdminAPIKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := aakcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aakcb *AdminAPIKeyCreateBulk) ExecX(ctx context.Context) {
	if err := aakcb.Exec(ctx); err != nil {
		panic(err)
	}
}
