// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/adminapikey"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/predicate"
	"github.com/google/uuid"
)

// AdminAPIKeyQuery is the builder for querying AdminAPIKey entities.
type AdminAPIKeyQuery struct {
	config
	ctx        *QueryContext
	order      []adminapikey.OrderOption
	inters     []Interceptor
	predicates []predicate.AdminAPIKey
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdminAPIKeyQuery builder.
func (aakq *AdminAPIKeyQuery) Where(ps ...predicate.AdminAPIKey) *AdminAPIKeyQuery {
	aakq.predicates = append(aakq.predicates, ps...)
	return aakq
}

// Limit the number of records to be returned by this query.
func (aakq *AdminAPIKeyQuery) Limit(limit int) *AdminAPIKeyQuery {
	aakq.ctx.Limit = &limit
	return aakq
}

// Offset to start from.
func (aakq *AdminAPIKeyQuery) Offset(offset int) *AdminAPIKeyQuery {
	aakq.ctx.Offset = &offset
	return aakq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aakq *AdminAPIKeyQuery) Unique(unique bool) *AdminAPIKeyQuery {
	aakq.ctx.Unique = &unique
	return aakq
}

// Order specifies how the records should be ordered.
func (aakq *AdminAPIKeyQuery) Order(o ...adminapikey.OrderOption) *AdminAPIKeyQuery {
	aakq.order = append(aakq.order, o...)
	return aakq
}

// First returns the first AdminAPIKey entity from the query.
// Returns a *NotFoundError when no AdminAPIKey was found.
func (aakq *AdminAPIKeyQuery) First(ctx context.Context) (*AdminAPIKey, error) {
	nodes, err := aakq.Limit(1).All(setContextOp(ctx, aakq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{adminapikey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aakq *AdminAPIKeyQuery) FirstX(ctx context.Context) *AdminAPIKey {
	node, err := aakq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdminAPIKey ID from the query.
// Returns a *NotFoundError when no AdminAPIKey ID was found.
func (aakq *AdminAPIKeyQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aakq.Limit(1).IDs(setContextOp(ctx, aakq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{adminapikey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aakq *AdminAPIKeyQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := aakq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdminAPIKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdminAPIKey entity is found.
// Returns a *NotFoundError when no AdminAPIKey entities are found.
func (aakq *AdminAPIKeyQuery) Only(ctx context.Context) (*AdminAPIKey, error) {
	nodes, err := aakq.Limit(2).All(setContextOp(ctx, aakq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{adminapikey.Label}
	default:
		return nil, &NotSingularError{adminapikey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aakq *AdminAPIKeyQuery) OnlyX(ctx context.Context) *AdminAPIKey {
	node, err := aakq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdminAPIKey ID in the query.
// Returns a *NotSingularError when more than one AdminAPIKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (aakq *AdminAPIKeyQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aakq.Limit(2).IDs(setContextOp(ctx, aakq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{adminapikey.Label}
	default:
		err = &NotSingularError{adminapikey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aakq *AdminAPIKeyQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := aakq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdminAPIKeys.
func (aakq *AdminAPIKeyQuery) All(ctx context.Context) ([]*AdminAPIKey, error) {
	ctx = setContextOp(ctx, aakq.ctx, ent.OpQueryAll)
	if err := aakq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AdminAPIKey, *AdminAPIKeyQuery]()
	return withInterceptors[[]*AdminAPIKey](ctx, aakq, qr, aakq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aakq *AdminAPIKeyQuery) AllX(ctx context.Context) []*AdminAPIKey {
	nodes, err := aakq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdminAPIKey IDs.
func (aakq *AdminAPIKeyQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if aakq.ctx.Unique == nil && aakq.path != nil {
		aakq.Unique(true)
	}
	ctx = setContextOp(ctx, aakq.ctx, ent.OpQueryIDs)
	if err = aakq.Select(adminapikey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aakq *AdminAPIKeyQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := aakq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aakq *AdminAPIKeyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aakq.ctx, ent.OpQueryCount)
	if err := aakq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aakq, querierCount[*AdminAPIKeyQuery](), aakq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aakq *AdminAPIKeyQuery) CountX(ctx context.Context) int {
	count, err := aakq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aakq *AdminAPIKeyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aakq.ctx, ent.OpQueryExist)
	switch _, err := aakq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aakq *AdminAPIKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := aakq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdminAPIKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aakq *AdminAPIKeyQuery) Clone() *AdminAPIKeyQuery {
	if aakq == nil {
		return nil
	}
	return &AdminAPIKeyQuery{
		config:     aakq.config,
		ctx:        aakq.ctx.Clone(),
		order:      append([]adminapikey.OrderOption{}, aakq.order...),
		inters:     append([]Interceptor{}, aakq.inters...),
		predicates: append([]predicate.AdminAPIKey{}, aakq.predicates...),
		// clone intermediate query.
		sql:  aakq.sql.Clone(),
		path: aakq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdminAPIKey.Query().
//		GroupBy(adminapikey.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aakq *AdminAPIKeyQuery) GroupBy(field string, fields ...string) *AdminAPIKeyGroupBy {
	aakq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AdminAPIKeyGroupBy{build: aakq}
	grbuild.flds = &aakq.ctx.Fields
	grbuild.label = adminapikey.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.AdminAPIKey.Query().
//		Select(adminapikey.FieldName).
//		Scan(ctx, &v)
func (aakq *AdminAPIKeyQuery) Select(fields ...string) *AdminAPIKeySelect {
	aakq.ctx.Fields = append(aakq.ctx.Fields, fields...)
	sbuild := &AdminAPIKeySelect{AdminAPIKeyQuery: aakq}
	sbuild.label = adminapikey.Label
	sbuild.flds, sbuild.scan = &aakq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AdminAPIKeySelect configured with the given aggregations.
func (aakq *AdminAPIKeyQuery) Aggregate(fns ...AggregateFunc) *AdminAPIKeySelect {
	return aakq.Select().Aggregate(fns...)
}

func (aakq *AdminAPIKeyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aakq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aakq); err != nil {
				return err
			}
		}
	}
	for _, f := range aakq.ctx.Fields {
		if !adminapikey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aakq.path != nil {
		prev, err := aakq.path(ctx)
		if err != nil {
			return err
		}
		aakq.sql = prev
	}
	return nil
}

func (aakq *AdminAPIKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdminAPIKey, error) {
	var (
		nodes = []*AdminAPIKey{}
		_spec = aakq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AdminAPIKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AdminAPIKey{config: aakq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aakq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aakq *AdminAPIKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aakq.querySpec()
	_spec.Node.Columns = aakq.ctx.Fields
	if len(aakq.ctx.Fields) > 0 {
		_spec.Unique = aakq.ctx.Unique != nil && *aakq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aakq.driver, _spec)
}

func (aakq *AdminAPIKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(adminapikey.Table, adminapikey.Columns, sqlgraph.NewFieldSpec(adminapikey.FieldID, field.TypeUUID))
	_spec.From = aakq.sql
	if unique := aakq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aakq.path != nil {
		_spec.Unique = true
	}
	if fields := aakq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminapikey.FieldID)
		for i := range fields {
			if fields[i] != adminapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aakq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aakq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aakq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aakq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aakq *AdminAPIKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aakq.driver.Dialect())
	t1 := builder.Table(adminapikey.Table)
	columns := aakq.ctx.Fields
	if len(columns) == 0 {
		columns = adminapikey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aakq.sql != nil {
		selector = aakq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aakq.ctx.Unique != nil && *aakq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aakq.predicates {
		p(selector)
	}
	for _, p := range aakq.order {
		p(selector)
	}
	if offset := aakq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aakq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AdminAPIKeyGroupBy is the group-by builder for AdminAPIKey entities.
type AdminAPIKeyGroupBy struct {
	selector
	build *AdminAPIKeyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aakgb *AdminAPIKeyGroupBy) Aggregate(fns ...AggregateFunc) *AdminAPIKeyGroupBy {
	aakgb.fns = append(aakgb.fns, fns...)
	return aakgb
}

// Scan applies the selector query and scans the result into the given value.
func (aakgb *AdminAPIKeyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aakgb.build.ctx, ent.OpQueryGroupBy)
	if err := aakgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminAPIKeyQuery, *AdminAPIKeyGroupBy](ctx, aakgb.build, aakgb, aakgb.build.inters, v)
}

func (aakgb *AdminAPIKeyGroupBy) sqlScan(ctx context.Context, root *AdminAPIKeyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aakgb.fns))
	for _, fn := range aakgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aakgb.flds)+len(aakgb.fns))
		for _, f := range *aakgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aakgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aakgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AdminAPIKeySelect is the builder for selecting fields of AdminAPIKey entities.
type AdminAPIKeySelect struct {
	*AdminAPIKeyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aaks *AdminAPIKeySelect) Aggregate(fns ...AggregateFunc) *AdminAPIKeySelect {
	aaks.fns = append(aaks.fns, fns...)
	return aaks
}

// Scan applies the selector query and scans the result into the given value.
func (aaks *AdminAPIKeySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aaks.ctx, ent.OpQuerySelect)
	if err := aaks.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminAPIKeyQuery, *AdminAPIKeySelect](ctx, aaks.AdminAPIKeyQuery, aaks, aaks.inters, v)
}

func (aaks *AdminAPIKeySelect) sqlScan(ctx context.Context, root *AdminAPIKeyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aaks.fns))
	for _, fn := range aaks.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aaks.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aaks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
