// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/adminapikey"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/predicate"
)

// AdminAPIKeyUpdate is the builder for updating AdminAPIKey entities.
type AdminAPIKeyUpdate struct {
	config
	hooks    []Hook
	mutation *AdminAPIKeyMutation
}

// Where appends a list predicates to the AdminAPIKeyUpdate builder.
func (_u *AdminAPIKeyUpdate) Where(ps ...predicate.AdminAPIKey) *AdminAPIKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AdminAPIKeyUpdate) SetName(v string) *AdminAPIKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdminAPIKeyUpdate) SetNillableName(v *string) *AdminAPIKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *AdminAPIKeyUpdate) SetKeyHash(v string) *AdminAPIKeyUpdate {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *AdminAPIKeyUpdate) SetNillableKeyHash(v *string) *AdminAPIKeyUpdate {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *AdminAPIKeyUpdate) SetKeyPrefix(v string) *AdminAPIKeyUpdate {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *AdminAPIKeyUpdate) SetNillableKeyPrefix(v *string) *AdminAPIKeyUpdate {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AdminAPIKeyUpdate) SetIsActive(v bool) *AdminAPIKeyUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AdminAPIKeyUpdate) SetNillableIsActive(v *bool) *AdminAPIKeyUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AdminAPIKeyUpdate) SetLastUsedAt(v time.Time) *AdminAPIKeyUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AdminAPIKeyUpdate) SetNillableLastUsedAt(v *time.Time) *AdminAPIKeyUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AdminAPIKeyUpdate) ClearLastUsedAt() *AdminAPIKeyUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AdminAPIKeyUpdate) SetExpiresAt(v time.Time) *AdminAPIKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AdminAPIKeyUpdate) SetNillableExpiresAt(v *time.Time) *AdminAPIKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AdminAPIKeyUpdate) ClearExpiresAt() *AdminAPIKeyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminAPIKeyUpdate) SetUpdatedAt(v time.Time) *AdminAPIKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminAPIKeyMutation object of the builder.
func (_u *AdminAPIKeyUpdate) Mutation() *AdminAPIKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminAPIKeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminAPIKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminAPIKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminAPIKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminAPIKeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminAPIKeyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := adminapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminAPIKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := adminapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "AdminAPIKey.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyPrefix(); ok {
		if err := adminapikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "AdminAPIKey.key_prefix": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminAPIKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminapikey.Table, adminapikey.Columns, sqlgraph.NewFieldSpec(adminapikey.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adminapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(adminapikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(adminapikey.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(adminapikey.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(adminapikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(adminapikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(adminapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(adminapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminAPIKeyUpdateOne is the builder for updating a single AdminAPIKey entity.
type AdminAPIKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminAPIKeyMutation
}

// SetName sets the "name" field.
func (_u *AdminAPIKeyUpdateOne) SetName(v string) *AdminAPIKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdminAPIKeyUpdateOne) SetNillableName(v *string) *AdminAPIKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *AdminAPIKeyUpdateOne) SetKeyHash(v string) *AdminAPIKeyUpdateOne {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *AdminAPIKeyUpdateOne) SetNillableKeyHash(v *string) *AdminAPIKeyUpdateOne {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *AdminAPIKeyUpdateOne) SetKeyPrefix(v string) *AdminAPIKeyUpdateOne {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *AdminAPIKeyUpdateOne) SetNillableKeyPrefix(v *string) *AdminAPIKeyUpdateOne {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AdminAPIKeyUpdateOne) SetIsActive(v bool) *AdminAPIKeyUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AdminAPIKeyUpdateOne) SetNillableIsActive(v *bool) *AdminAPIKeyUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AdminAPIKeyUpdateOne) SetLastUsedAt(v time.Time) *AdminAPIKeyUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AdminAPIKeyUpdateOne) SetNillableLastUsedAt(v *time.Time) *AdminAPIKeyUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AdminAPIKeyUpdateOne) ClearLastUsedAt() *AdminAPIKeyUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AdminAPIKeyUpdateOne) SetExpiresAt(v time.Time) *AdminAPIKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AdminAPIKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *AdminAPIKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AdminAPIKeyUpdateOne) ClearExpiresAt() *AdminAPIKeyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminAPIKeyUpdateOne) SetUpdatedAt(v time.Time) *AdminAPIKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminAPIKeyMutation object of the builder.
func (_u *AdminAPIKeyUpdateOne) Mutation() *AdminAPIKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminAPIKeyUpdate builder.
func (_u *AdminAPIKeyUpdateOne) Where(ps ...predicate.AdminAPIKey) *AdminAPIKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminAPIKeyUpdateOne) Select(field string, fields ...string) *AdminAPIKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminAPIKey entity.
func (_u *AdminAPIKeyUpdateOne) Save(ctx context.Context) (*AdminAPIKey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminAPIKeyUpdateOne) SaveX(ctx context.Context) *AdminAPIKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminAPIKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminAPIKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminAPIKeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminAPIKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := adminapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminAPIKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := adminapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "AdminAPIKey.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyPrefix(); ok {
		if err := adminapikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "AdminAPIKey.key_prefix": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminAPIKeyUpdateOne) sqlSave(ctx context.Context) (_node *AdminAPIKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminapikey.Table, adminapikey.Columns, sqlgraph.NewFieldSpec(adminapikey.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminAPIKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminapikey.FieldID)
		for _, f := range fields {
			if !adminapikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adminapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(adminapikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(adminapikey.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(adminapikey.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(adminapikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(adminapikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(adminapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(adminapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AdminAPIKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
