// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dev-hyunsang/home-library-backend/lib/ent/adminapikey"
	"github.com/google/uuid"
)

// AdminAPIKey is the model entity for the AdminAPIKey schema.
type AdminAPIKey struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// API Key 이름/설명
	Name string `json:"name,omitempty"`
	// 해시된 API Key
	KeyHash string `json:"key_hash,omitempty"`
	// API Key 앞 8자리 (식별용)
	KeyPrefix string `json:"key_prefix,omitempty"`
	// 활성화 여부
	IsActive bool `json:"is_active,omitempty"`
	// 마지막 사용 시간
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// 만료 시간 (null이면 무제한)
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// 생성 시간
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 수정 시간
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminAPIKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminapikey.FieldIsActive:
			values[i] = new(sql.NullBool)
		case adminapikey.FieldName, adminapikey.FieldKeyHash, adminapikey.FieldKeyPrefix:
			values[i] = new(sql.NullString)
		case adminapikey.FieldLastUsedAt, adminapikey.FieldExpiresAt, adminapikey.FieldCreatedAt, adminapikey.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case adminapikey.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminAPIKey fields.
func (aak *AdminAPIKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminapikey.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				aak.ID = *value
			}
		case adminapikey.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				aak.Name = value.String
			}
		case adminapikey.FieldKeyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_hash", values[i])
			} else if value.Valid {
				aak.KeyHash = value.String
			}
		case adminapikey.FieldKeyPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_prefix", values[i])
			} else if value.Valid {
				aak.KeyPrefix = value.String
			}
		case adminapikey.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				aak.IsActive = value.Bool
			}
		case adminapikey.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				aak.LastUsedAt = new(time.Time)
				*aak.LastUsedAt = value.Time
			}
		case adminapikey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				aak.ExpiresAt = new(time.Time)
				*aak.ExpiresAt = value.Time
			}
		case adminapikey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				aak.CreatedAt = value.Time
			}
		case adminapikey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				aak.UpdatedAt = value.Time
			}
		default:
			aak.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminAPIKey.
// This includes values selected through modifiers, order, etc.
func (aak *AdminAPIKey) Value(name string) (ent.Value, error) {
	return aak.selectValues.Get(name)
}

// Update returns a builder for updating this AdminAPIKey.
// Note that you need to call AdminAPIKey.Unwrap() before calling this method if this AdminAPIKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (aak *AdminAPIKey) Update() *AdminAPIKeyUpdateOne {
	return NewAdminAPIKeyClient(aak.config).UpdateOne(aak)
}

// Unwrap unwraps the AdminAPIKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (aak *AdminAPIKey) Unwrap() *AdminAPIKey {
	_tx, ok := aak.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminAPIKey is not a transactional entity")
	}
	aak.config.driver = _tx.drv
	return aak
}

// String implements the fmt.Stringer.
func (aak *AdminAPIKey) String() string {
	var builder strings.Builder
	builder.WriteString("AdminAPIKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", aak.ID))
	builder.WriteString("name=")
	builder.WriteString(aak.Name)
	builder.WriteString(", ")
	builder.WriteString("key_hash=")
	builder.WriteString(aak.KeyHash)
	builder.WriteString(", ")
	builder.WriteString("key_prefix=")
	builder.WriteString(aak.KeyPrefix)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", aak.IsActive))
	builder.WriteString(", ")
	if v := aak.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := aak.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(aak.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(aak.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AdminAPIKeys is a parsable slice of AdminAPIKey.
type AdminAPIKeys []*AdminAPIKey
