// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/adminapikey"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/predicate"
)

// AdminAPIKeyDelete is the builder for deleting a AdminAPIKey entity.
type AdminAPIKeyDelete struct {
	config
	hooks    []Hook
	mutation *AdminAPIKeyMutation
}

// Where appends a list predicates to the AdminAPIKeyDelete builder.
func (_d *AdminAPIKeyDelete) Where(ps ...predicate.AdminAPIKey) *AdminAPIKeyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AdminAPIKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminAPIKeyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AdminAPIKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(adminapikey.Table, sqlgraph.NewFieldSpec(adminapikey.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AdminAPIKeyDeleteOne is the builder for deleting a single AdminAPIKey entity.
type AdminAPIKeyDeleteOne struct {
	_d *AdminAPIKeyDelete
}

// Where appends a list predicates to the AdminAPIKeyDelete builder.
func (_d *AdminAPIKeyDeleteOne) Where(ps ...predicate.AdminAPIKey) *AdminAPIKeyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AdminAPIKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{adminapikey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminAPIKeyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
