// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/book"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/bookmark"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/predicate"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/review"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/user"
	"github.com/google/uuid"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBookTitle sets the "book_title" field.
func (_u *BookUpdate) SetBookTitle(v string) *BookUpdate {
	_u.mutation.SetBookTitle(v)
	return _u
}

// SetNillableBookTitle sets the "book_title" field if the given value is not nil.
func (_u *BookUpdate) SetNillableBookTitle(v *string) *BookUpdate {
	if v != nil {
		_u.SetBookTitle(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *BookUpdate) SetAuthor(v string) *BookUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *BookUpdate) SetNillableAuthor(v *string) *BookUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetBookIsbn sets the "book_isbn" field.
func (_u *BookUpdate) SetBookIsbn(v string) *BookUpdate {
	_u.mutation.SetBookIsbn(v)
	return _u
}

// SetNillableBookIsbn sets the "book_isbn" field if the given value is not nil.
func (_u *BookUpdate) SetNillableBookIsbn(v *string) *BookUpdate {
	if v != nil {
		_u.SetBookIsbn(*v)
	}
	return _u
}

// ClearBookIsbn clears the value of the "book_isbn" field.
func (_u *BookUpdate) ClearBookIsbn() *BookUpdate {
	_u.mutation.ClearBookIsbn()
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *BookUpdate) SetThumbnailURL(v string) *BookUpdate {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *BookUpdate) SetNillableThumbnailURL(v *string) *BookUpdate {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *BookUpdate) ClearThumbnailURL() *BookUpdate {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BookUpdate) SetStatus(v int) *BookUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BookUpdate) SetNillableStatus(v *int) *BookUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *BookUpdate) AddStatus(v int) *BookUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BookUpdate) SetCreatedAt(v time.Time) *BookUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCreatedAt(v *time.Time) *BookUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdate) SetUpdatedAt(v time.Time) *BookUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *BookUpdate) SetOwnerID(id uuid.UUID) *BookUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *BookUpdate) SetOwner(v *User) *BookUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (_u *BookUpdate) AddReviewIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the Review entity.
func (_u *BookUpdate) AddReviews(v ...*Review) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// AddBookmarkIDs adds the "bookmarks" edge to the Bookmark entity by IDs.
func (_u *BookUpdate) AddBookmarkIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.AddBookmarkIDs(ids...)
	return _u
}

// AddBookmarks adds the "bookmarks" edges to the Bookmark entity.
func (_u *BookUpdate) AddBookmarks(v ...*Bookmark) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookmarkIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdate) Mutation() *BookMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *BookUpdate) ClearOwner() *BookUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (_u *BookUpdate) ClearReviews() *BookUpdate {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (_u *BookUpdate) RemoveReviewIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to Review entities.
func (_u *BookUpdate) RemoveReviews(v ...*Review) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// ClearBookmarks clears all "bookmarks" edges to the Bookmark entity.
func (_u *BookUpdate) ClearBookmarks() *BookUpdate {
	_u.mutation.ClearBookmarks()
	return _u
}

// RemoveBookmarkIDs removes the "bookmarks" edge to Bookmark entities by IDs.
func (_u *BookUpdate) RemoveBookmarkIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.RemoveBookmarkIDs(ids...)
	return _u
}

// RemoveBookmarks removes "bookmarks" edges to Bookmark entities.
func (_u *BookUpdate) RemoveBookmarks(v ...*Bookmark) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookmarkIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdate) check() error {
	if v, ok := _u.mutation.BookTitle(); ok {
		if err := book.BookTitleValidator(v); err != nil {
			return &ValidationError{Name: "book_title", err: fmt.Errorf(`ent: validator failed for field "Book.book_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := book.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Book.author": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Book.owner"`)
	}
	return nil
}

func (_u *BookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BookTitle(); ok {
		_spec.SetField(book.FieldBookTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.BookIsbn(); ok {
		_spec.SetField(book.FieldBookIsbn, field.TypeString, value)
	}
	if _u.mutation.BookIsbnCleared() {
		_spec.ClearField(book.FieldBookIsbn, field.TypeString)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(book.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(book.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(book.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(book.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(book.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.OwnerTable,
			Columns: []string{book.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.OwnerTable,
			Columns: []string{book.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookmarksIDs(); len(nodes) > 0 && !_u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookmarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetBookTitle sets the "book_title" field.
func (_u *BookUpdateOne) SetBookTitle(v string) *BookUpdateOne {
	_u.mutation.SetBookTitle(v)
	return _u
}

// SetNillableBookTitle sets the "book_title" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableBookTitle(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetBookTitle(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *BookUpdateOne) SetAuthor(v string) *BookUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableAuthor(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetBookIsbn sets the "book_isbn" field.
func (_u *BookUpdateOne) SetBookIsbn(v string) *BookUpdateOne {
	_u.mutation.SetBookIsbn(v)
	return _u
}

// SetNillableBookIsbn sets the "book_isbn" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableBookIsbn(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetBookIsbn(*v)
	}
	return _u
}

// ClearBookIsbn clears the value of the "book_isbn" field.
func (_u *BookUpdateOne) ClearBookIsbn() *BookUpdateOne {
	_u.mutation.ClearBookIsbn()
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *BookUpdateOne) SetThumbnailURL(v string) *BookUpdateOne {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableThumbnailURL(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *BookUpdateOne) ClearThumbnailURL() *BookUpdateOne {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BookUpdateOne) SetStatus(v int) *BookUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableStatus(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *BookUpdateOne) AddStatus(v int) *BookUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BookUpdateOne) SetCreatedAt(v time.Time) *BookUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCreatedAt(v *time.Time) *BookUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdateOne) SetUpdatedAt(v time.Time) *BookUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *BookUpdateOne) SetOwnerID(id uuid.UUID) *BookUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *BookUpdateOne) SetOwner(v *User) *BookUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (_u *BookUpdateOne) AddReviewIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the Review entity.
func (_u *BookUpdateOne) AddReviews(v ...*Review) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// AddBookmarkIDs adds the "bookmarks" edge to the Bookmark entity by IDs.
func (_u *BookUpdateOne) AddBookmarkIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.AddBookmarkIDs(ids...)
	return _u
}

// AddBookmarks adds the "bookmarks" edges to the Bookmark entity.
func (_u *BookUpdateOne) AddBookmarks(v ...*Bookmark) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookmarkIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdateOne) Mutation() *BookMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *BookUpdateOne) ClearOwner() *BookUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (_u *BookUpdateOne) ClearReviews() *BookUpdateOne {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (_u *BookUpdateOne) RemoveReviewIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to Review entities.
func (_u *BookUpdateOne) RemoveReviews(v ...*Review) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// ClearBookmarks clears all "bookmarks" edges to the Bookmark entity.
func (_u *BookUpdateOne) ClearBookmarks() *BookUpdateOne {
	_u.mutation.ClearBookmarks()
	return _u
}

// RemoveBookmarkIDs removes the "bookmarks" edge to Bookmark entities by IDs.
func (_u *BookUpdateOne) RemoveBookmarkIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.RemoveBookmarkIDs(ids...)
	return _u
}

// RemoveBookmarks removes "bookmarks" edges to Bookmark entities.
func (_u *BookUpdateOne) RemoveBookmarks(v ...*Bookmark) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookmarkIDs(ids...)
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Book entity.
func (_u *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdateOne) check() error {
	if v, ok := _u.mutation.BookTitle(); ok {
		if err := book.BookTitleValidator(v); err != nil {
			return &ValidationError{Name: "book_title", err: fmt.Errorf(`ent: validator failed for field "Book.book_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := book.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Book.author": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Book.owner"`)
	}
	return nil
}

func (_u *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BookTitle(); ok {
		_spec.SetField(book.FieldBookTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.BookIsbn(); ok {
		_spec.SetField(book.FieldBookIsbn, field.TypeString, value)
	}
	if _u.mutation.BookIsbnCleared() {
		_spec.ClearField(book.FieldBookIsbn, field.TypeString)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(book.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(book.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(book.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(book.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(book.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.OwnerTable,
			Columns: []string{book.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.OwnerTable,
			Columns: []string{book.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookmarksIDs(); len(nodes) > 0 && !_u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookmarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Book{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
