// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/book"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/bookmark"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/predicate"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/review"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/user"
	"github.com/google/uuid"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (bu *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetBookTitle sets the "book_title" field.
func (bu *BookUpdate) SetBookTitle(s string) *BookUpdate {
	bu.mutation.SetBookTitle(s)
	return bu
}

// SetNillableBookTitle sets the "book_title" field if the given value is not nil.
func (bu *BookUpdate) SetNillableBookTitle(s *string) *BookUpdate {
	if s != nil {
		bu.SetBookTitle(*s)
	}
	return bu
}

// SetAuthor sets the "author" field.
func (bu *BookUpdate) SetAuthor(s string) *BookUpdate {
	bu.mutation.SetAuthor(s)
	return bu
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (bu *BookUpdate) SetNillableAuthor(s *string) *BookUpdate {
	if s != nil {
		bu.SetAuthor(*s)
	}
	return bu
}

// SetBookIsbn sets the "book_isbn" field.
func (bu *BookUpdate) SetBookIsbn(s string) *BookUpdate {
	bu.mutation.SetBookIsbn(s)
	return bu
}

// SetNillableBookIsbn sets the "book_isbn" field if the given value is not nil.
func (bu *BookUpdate) SetNillableBookIsbn(s *string) *BookUpdate {
	if s != nil {
		bu.SetBookIsbn(*s)
	}
	return bu
}

// ClearBookIsbn clears the value of the "book_isbn" field.
func (bu *BookUpdate) ClearBookIsbn() *BookUpdate {
	bu.mutation.ClearBookIsbn()
	return bu
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (bu *BookUpdate) SetThumbnailURL(s string) *BookUpdate {
	bu.mutation.SetThumbnailURL(s)
	return bu
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (bu *BookUpdate) SetNillableThumbnailURL(s *string) *BookUpdate {
	if s != nil {
		bu.SetThumbnailURL(*s)
	}
	return bu
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (bu *BookUpdate) ClearThumbnailURL() *BookUpdate {
	bu.mutation.ClearThumbnailURL()
	return bu
}

// SetStatus sets the "status" field.
func (bu *BookUpdate) SetStatus(i int) *BookUpdate {
	bu.mutation.ResetStatus()
	bu.mutation.SetStatus(i)
	return bu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (bu *BookUpdate) SetNillableStatus(i *int) *BookUpdate {
	if i != nil {
		bu.SetStatus(*i)
	}
	return bu
}

// AddStatus adds i to the "status" field.
func (bu *BookUpdate) AddStatus(i int) *BookUpdate {
	bu.mutation.AddStatus(i)
	return bu
}

// SetCreatedAt sets the "created_at" field.
func (bu *BookUpdate) SetCreatedAt(t time.Time) *BookUpdate {
	bu.mutation.SetCreatedAt(t)
	return bu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bu *BookUpdate) SetNillableCreatedAt(t *time.Time) *BookUpdate {
	if t != nil {
		bu.SetCreatedAt(*t)
	}
	return bu
}

// SetUpdatedAt sets the "updated_at" field.
func (bu *BookUpdate) SetUpdatedAt(t time.Time) *BookUpdate {
	bu.mutation.SetUpdatedAt(t)
	return bu
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (bu *BookUpdate) SetOwnerID(id uuid.UUID) *BookUpdate {
	bu.mutation.SetOwnerID(id)
	return bu
}

// SetOwner sets the "owner" edge to the User entity.
func (bu *BookUpdate) SetOwner(u *User) *BookUpdate {
	return bu.SetOwnerID(u.ID)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (bu *BookUpdate) AddReviewIDs(ids ...uuid.UUID) *BookUpdate {
	bu.mutation.AddReviewIDs(ids...)
	return bu
}

// AddReviews adds the "reviews" edges to the Review entity.
func (bu *BookUpdate) AddReviews(r ...*Review) *BookUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return bu.AddReviewIDs(ids...)
}

// AddBookmarkIDs adds the "bookmarks" edge to the Bookmark entity by IDs.
func (bu *BookUpdate) AddBookmarkIDs(ids ...uuid.UUID) *BookUpdate {
	bu.mutation.AddBookmarkIDs(ids...)
	return bu
}

// AddBookmarks adds the "bookmarks" edges to the Bookmark entity.
func (bu *BookUpdate) AddBookmarks(b ...*Bookmark) *BookUpdate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return bu.AddBookmarkIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (bu *BookUpdate) Mutation() *BookMutation {
	return bu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (bu *BookUpdate) ClearOwner() *BookUpdate {
	bu.mutation.ClearOwner()
	return bu
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (bu *BookUpdate) ClearReviews() *BookUpdate {
	bu.mutation.ClearReviews()
	return bu
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (bu *BookUpdate) RemoveReviewIDs(ids ...uuid.UUID) *BookUpdate {
	bu.mutation.RemoveReviewIDs(ids...)
	return bu
}

// RemoveReviews removes "reviews" edges to Review entities.
func (bu *BookUpdate) RemoveReviews(r ...*Review) *BookUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return bu.RemoveReviewIDs(ids...)
}

// ClearBookmarks clears all "bookmarks" edges to the Bookmark entity.
func (bu *BookUpdate) ClearBookmarks() *BookUpdate {
	bu.mutation.ClearBookmarks()
	return bu
}

// RemoveBookmarkIDs removes the "bookmarks" edge to Bookmark entities by IDs.
func (bu *BookUpdate) RemoveBookmarkIDs(ids ...uuid.UUID) *BookUpdate {
	bu.mutation.RemoveBookmarkIDs(ids...)
	return bu
}

// RemoveBookmarks removes "bookmarks" edges to Bookmark entities.
func (bu *BookUpdate) RemoveBookmarks(b ...*Bookmark) *BookUpdate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return bu.RemoveBookmarkIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BookUpdate) Save(ctx context.Context) (int, error) {
	bu.defaults()
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BookUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BookUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bu *BookUpdate) defaults() {
	if _, ok := bu.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		bu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BookUpdate) check() error {
	if v, ok := bu.mutation.BookTitle(); ok {
		if err := book.BookTitleValidator(v); err != nil {
			return &ValidationError{Name: "book_title", err: fmt.Errorf(`ent: validator failed for field "Book.book_title": %w`, err)}
		}
	}
	if v, ok := bu.mutation.Author(); ok {
		if err := book.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Book.author": %w`, err)}
		}
	}
	if bu.mutation.OwnerCleared() && len(bu.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Book.owner"`)
	}
	return nil
}

func (bu *BookUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.BookTitle(); ok {
		_spec.SetField(book.FieldBookTitle, field.TypeString, value)
	}
	if value, ok := bu.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if value, ok := bu.mutation.BookIsbn(); ok {
		_spec.SetField(book.FieldBookIsbn, field.TypeString, value)
	}
	if bu.mutation.BookIsbnCleared() {
		_spec.ClearField(book.FieldBookIsbn, field.TypeString)
	}
	if value, ok := bu.mutation.ThumbnailURL(); ok {
		_spec.SetField(book.FieldThumbnailURL, field.TypeString, value)
	}
	if bu.mutation.ThumbnailURLCleared() {
		_spec.ClearField(book.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := bu.mutation.Status(); ok {
		_spec.SetField(book.FieldStatus, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedStatus(); ok {
		_spec.AddField(book.FieldStatus, field.TypeInt, value)
	}
	if value, ok := bu.mutation.CreatedAt(); ok {
		_spec.SetField(book.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := bu.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if bu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.OwnerTable,
			Columns: []string{book.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.OwnerTable,
			Columns: []string{book.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !bu.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemovedBookmarksIDs(); len(nodes) > 0 && !bu.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.BookmarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetBookTitle sets the "book_title" field.
func (buo *BookUpdateOne) SetBookTitle(s string) *BookUpdateOne {
	buo.mutation.SetBookTitle(s)
	return buo
}

// SetNillableBookTitle sets the "book_title" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableBookTitle(s *string) *BookUpdateOne {
	if s != nil {
		buo.SetBookTitle(*s)
	}
	return buo
}

// SetAuthor sets the "author" field.
func (buo *BookUpdateOne) SetAuthor(s string) *BookUpdateOne {
	buo.mutation.SetAuthor(s)
	return buo
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableAuthor(s *string) *BookUpdateOne {
	if s != nil {
		buo.SetAuthor(*s)
	}
	return buo
}

// SetBookIsbn sets the "book_isbn" field.
func (buo *BookUpdateOne) SetBookIsbn(s string) *BookUpdateOne {
	buo.mutation.SetBookIsbn(s)
	return buo
}

// SetNillableBookIsbn sets the "book_isbn" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableBookIsbn(s *string) *BookUpdateOne {
	if s != nil {
		buo.SetBookIsbn(*s)
	}
	return buo
}

// ClearBookIsbn clears the value of the "book_isbn" field.
func (buo *BookUpdateOne) ClearBookIsbn() *BookUpdateOne {
	buo.mutation.ClearBookIsbn()
	return buo
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (buo *BookUpdateOne) SetThumbnailURL(s string) *BookUpdateOne {
	buo.mutation.SetThumbnailURL(s)
	return buo
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableThumbnailURL(s *string) *BookUpdateOne {
	if s != nil {
		buo.SetThumbnailURL(*s)
	}
	return buo
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (buo *BookUpdateOne) ClearThumbnailURL() *BookUpdateOne {
	buo.mutation.ClearThumbnailURL()
	return buo
}

// SetStatus sets the "status" field.
func (buo *BookUpdateOne) SetStatus(i int) *BookUpdateOne {
	buo.mutation.ResetStatus()
	buo.mutation.SetStatus(i)
	return buo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableStatus(i *int) *BookUpdateOne {
	if i != nil {
		buo.SetStatus(*i)
	}
	return buo
}

// AddStatus adds i to the "status" field.
func (buo *BookUpdateOne) AddStatus(i int) *BookUpdateOne {
	buo.mutation.AddStatus(i)
	return buo
}

// SetCreatedAt sets the "created_at" field.
func (buo *BookUpdateOne) SetCreatedAt(t time.Time) *BookUpdateOne {
	buo.mutation.SetCreatedAt(t)
	return buo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableCreatedAt(t *time.Time) *BookUpdateOne {
	if t != nil {
		buo.SetCreatedAt(*t)
	}
	return buo
}

// SetUpdatedAt sets the "updated_at" field.
func (buo *BookUpdateOne) SetUpdatedAt(t time.Time) *BookUpdateOne {
	buo.mutation.SetUpdatedAt(t)
	return buo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (buo *BookUpdateOne) SetOwnerID(id uuid.UUID) *BookUpdateOne {
	buo.mutation.SetOwnerID(id)
	return buo
}

// SetOwner sets the "owner" edge to the User entity.
func (buo *BookUpdateOne) SetOwner(u *User) *BookUpdateOne {
	return buo.SetOwnerID(u.ID)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (buo *BookUpdateOne) AddReviewIDs(ids ...uuid.UUID) *BookUpdateOne {
	buo.mutation.AddReviewIDs(ids...)
	return buo
}

// AddReviews adds the "reviews" edges to the Review entity.
func (buo *BookUpdateOne) AddReviews(r ...*Review) *BookUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return buo.AddReviewIDs(ids...)
}

// AddBookmarkIDs adds the "bookmarks" edge to the Bookmark entity by IDs.
func (buo *BookUpdateOne) AddBookmarkIDs(ids ...uuid.UUID) *BookUpdateOne {
	buo.mutation.AddBookmarkIDs(ids...)
	return buo
}

// AddBookmarks adds the "bookmarks" edges to the Bookmark entity.
func (buo *BookUpdateOne) AddBookmarks(b ...*Bookmark) *BookUpdateOne {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return buo.AddBookmarkIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (buo *BookUpdateOne) Mutation() *BookMutation {
	return buo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (buo *BookUpdateOne) ClearOwner() *BookUpdateOne {
	buo.mutation.ClearOwner()
	return buo
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (buo *BookUpdateOne) ClearReviews() *BookUpdateOne {
	buo.mutation.ClearReviews()
	return buo
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (buo *BookUpdateOne) RemoveReviewIDs(ids ...uuid.UUID) *BookUpdateOne {
	buo.mutation.RemoveReviewIDs(ids...)
	return buo
}

// RemoveReviews removes "reviews" edges to Review entities.
func (buo *BookUpdateOne) RemoveReviews(r ...*Review) *BookUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return buo.RemoveReviewIDs(ids...)
}

// ClearBookmarks clears all "bookmarks" edges to the Bookmark entity.
func (buo *BookUpdateOne) ClearBookmarks() *BookUpdateOne {
	buo.mutation.ClearBookmarks()
	return buo
}

// RemoveBookmarkIDs removes the "bookmarks" edge to Bookmark entities by IDs.
func (buo *BookUpdateOne) RemoveBookmarkIDs(ids ...uuid.UUID) *BookUpdateOne {
	buo.mutation.RemoveBookmarkIDs(ids...)
	return buo
}

// RemoveBookmarks removes "bookmarks" edges to Bookmark entities.
func (buo *BookUpdateOne) RemoveBookmarks(b ...*Bookmark) *BookUpdateOne {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return buo.RemoveBookmarkIDs(ids...)
}

// Where appends a list predicates to the BookUpdate builder.
func (buo *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Book entity.
func (buo *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	buo.defaults()
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BookUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (buo *BookUpdateOne) defaults() {
	if _, ok := buo.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		buo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BookUpdateOne) check() error {
	if v, ok := buo.mutation.BookTitle(); ok {
		if err := book.BookTitleValidator(v); err != nil {
			return &ValidationError{Name: "book_title", err: fmt.Errorf(`ent: validator failed for field "Book.book_title": %w`, err)}
		}
	}
	if v, ok := buo.mutation.Author(); ok {
		if err := book.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Book.author": %w`, err)}
		}
	}
	if buo.mutation.OwnerCleared() && len(buo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Book.owner"`)
	}
	return nil
}

func (buo *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.BookTitle(); ok {
		_spec.SetField(book.FieldBookTitle, field.TypeString, value)
	}
	if value, ok := buo.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if value, ok := buo.mutation.BookIsbn(); ok {
		_spec.SetField(book.FieldBookIsbn, field.TypeString, value)
	}
	if buo.mutation.BookIsbnCleared() {
		_spec.ClearField(book.FieldBookIsbn, field.TypeString)
	}
	if value, ok := buo.mutation.ThumbnailURL(); ok {
		_spec.SetField(book.FieldThumbnailURL, field.TypeString, value)
	}
	if buo.mutation.ThumbnailURLCleared() {
		_spec.ClearField(book.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := buo.mutation.Status(); ok {
		_spec.SetField(book.FieldStatus, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedStatus(); ok {
		_spec.AddField(book.FieldStatus, field.TypeInt, value)
	}
	if value, ok := buo.mutation.CreatedAt(); ok {
		_spec.SetField(book.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := buo.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if buo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.OwnerTable,
			Columns: []string{book.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.OwnerTable,
			Columns: []string{book.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !buo.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemovedBookmarksIDs(); len(nodes) > 0 && !buo.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.BookmarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookmarksTable,
			Columns: []string{book.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Book{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
