// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/emailverification"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/predicate"
)

// EmailVerificationUpdate is the builder for updating EmailVerification entities.
type EmailVerificationUpdate struct {
	config
	hooks    []Hook
	mutation *EmailVerificationMutation
}

// Where appends a list predicates to the EmailVerificationUpdate builder.
func (_u *EmailVerificationUpdate) Where(ps ...predicate.EmailVerification) *EmailVerificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *EmailVerificationUpdate) SetEmail(v string) *EmailVerificationUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmailVerificationUpdate) SetNillableEmail(v *string) *EmailVerificationUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *EmailVerificationUpdate) SetCode(v string) *EmailVerificationUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *EmailVerificationUpdate) SetNillableCode(v *string) *EmailVerificationUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EmailVerificationUpdate) SetExpiresAt(v time.Time) *EmailVerificationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EmailVerificationUpdate) SetNillableExpiresAt(v *time.Time) *EmailVerificationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetIsVerified sets the "is_verified" field.
func (_u *EmailVerificationUpdate) SetIsVerified(v bool) *EmailVerificationUpdate {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_u *EmailVerificationUpdate) SetNillableIsVerified(v *bool) *EmailVerificationUpdate {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// Mutation returns the EmailVerificationMutation object of the builder.
func (_u *EmailVerificationUpdate) Mutation() *EmailVerificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailVerificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailVerificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailVerificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailVerificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailVerificationUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := emailverification.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "EmailVerification.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := emailverification.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "EmailVerification.code": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailVerificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailverification.Table, emailverification.Columns, sqlgraph.NewFieldSpec(emailverification.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(emailverification.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(emailverification.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(emailverification.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(emailverification.FieldIsVerified, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailVerificationUpdateOne is the builder for updating a single EmailVerification entity.
type EmailVerificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailVerificationMutation
}

// SetEmail sets the "email" field.
func (_u *EmailVerificationUpdateOne) SetEmail(v string) *EmailVerificationUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmailVerificationUpdateOne) SetNillableEmail(v *string) *EmailVerificationUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *EmailVerificationUpdateOne) SetCode(v string) *EmailVerificationUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *EmailVerificationUpdateOne) SetNillableCode(v *string) *EmailVerificationUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EmailVerificationUpdateOne) SetExpiresAt(v time.Time) *EmailVerificationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EmailVerificationUpdateOne) SetNillableExpiresAt(v *time.Time) *EmailVerificationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetIsVerified sets the "is_verified" field.
func (_u *EmailVerificationUpdateOne) SetIsVerified(v bool) *EmailVerificationUpdateOne {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_u *EmailVerificationUpdateOne) SetNillableIsVerified(v *bool) *EmailVerificationUpdateOne {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// Mutation returns the EmailVerificationMutation object of the builder.
func (_u *EmailVerificationUpdateOne) Mutation() *EmailVerificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmailVerificationUpdate builder.
func (_u *EmailVerificationUpdateOne) Where(ps ...predicate.EmailVerification) *EmailVerificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailVerificationUpdateOne) Select(field string, fields ...string) *EmailVerificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailVerification entity.
func (_u *EmailVerificationUpdateOne) Save(ctx context.Context) (*EmailVerification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailVerificationUpdateOne) SaveX(ctx context.Context) *EmailVerification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailVerificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailVerificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailVerificationUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := emailverification.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "EmailVerification.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := emailverification.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "EmailVerification.code": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailVerificationUpdateOne) sqlSave(ctx context.Context) (_node *EmailVerification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailverification.Table, emailverification.Columns, sqlgraph.NewFieldSpec(emailverification.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailVerification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailverification.FieldID)
		for _, f := range fields {
			if !emailverification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailverification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(emailverification.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(emailverification.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(emailverification.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(emailverification.FieldIsVerified, field.TypeBool, value)
	}
	_node = &EmailVerification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
