// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/predicate"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/readingreminder"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/user"
	"github.com/google/uuid"
)

// ReadingReminderUpdate is the builder for updating ReadingReminder entities.
type ReadingReminderUpdate struct {
	config
	hooks    []Hook
	mutation *ReadingReminderMutation
}

// Where appends a list predicates to the ReadingReminderUpdate builder.
func (_u *ReadingReminderUpdate) Where(ps ...predicate.ReadingReminder) *ReadingReminderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReminderTime sets the "reminder_time" field.
func (_u *ReadingReminderUpdate) SetReminderTime(v string) *ReadingReminderUpdate {
	_u.mutation.SetReminderTime(v)
	return _u
}

// SetNillableReminderTime sets the "reminder_time" field if the given value is not nil.
func (_u *ReadingReminderUpdate) SetNillableReminderTime(v *string) *ReadingReminderUpdate {
	if v != nil {
		_u.SetReminderTime(*v)
	}
	return _u
}

// SetDayOfWeek sets the "day_of_week" field.
func (_u *ReadingReminderUpdate) SetDayOfWeek(v readingreminder.DayOfWeek) *ReadingReminderUpdate {
	_u.mutation.SetDayOfWeek(v)
	return _u
}

// SetNillableDayOfWeek sets the "day_of_week" field if the given value is not nil.
func (_u *ReadingReminderUpdate) SetNillableDayOfWeek(v *readingreminder.DayOfWeek) *ReadingReminderUpdate {
	if v != nil {
		_u.SetDayOfWeek(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *ReadingReminderUpdate) SetIsEnabled(v bool) *ReadingReminderUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *ReadingReminderUpdate) SetNillableIsEnabled(v *bool) *ReadingReminderUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ReadingReminderUpdate) SetMessage(v string) *ReadingReminderUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ReadingReminderUpdate) SetNillableMessage(v *string) *ReadingReminderUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReadingReminderUpdate) SetUpdatedAt(v time.Time) *ReadingReminderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ReadingReminderUpdate) SetOwnerID(id uuid.UUID) *ReadingReminderUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ReadingReminderUpdate) SetOwner(v *User) *ReadingReminderUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ReadingReminderMutation object of the builder.
func (_u *ReadingReminderUpdate) Mutation() *ReadingReminderMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ReadingReminderUpdate) ClearOwner() *ReadingReminderUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReadingReminderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReadingReminderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReadingReminderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReadingReminderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReadingReminderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := readingreminder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReadingReminderUpdate) check() error {
	if v, ok := _u.mutation.ReminderTime(); ok {
		if err := readingreminder.ReminderTimeValidator(v); err != nil {
			return &ValidationError{Name: "reminder_time", err: fmt.Errorf(`ent: validator failed for field "ReadingReminder.reminder_time": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DayOfWeek(); ok {
		if err := readingreminder.DayOfWeekValidator(v); err != nil {
			return &ValidationError{Name: "day_of_week", err: fmt.Errorf(`ent: validator failed for field "ReadingReminder.day_of_week": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReadingReminder.owner"`)
	}
	return nil
}

func (_u *ReadingReminderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(readingreminder.Table, readingreminder.Columns, sqlgraph.NewFieldSpec(readingreminder.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReminderTime(); ok {
		_spec.SetField(readingreminder.FieldReminderTime, field.TypeString, value)
	}
	if value, ok := _u.mutation.DayOfWeek(); ok {
		_spec.SetField(readingreminder.FieldDayOfWeek, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(readingreminder.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(readingreminder.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(readingreminder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   readingreminder.OwnerTable,
			Columns: []string{readingreminder.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   readingreminder.OwnerTable,
			Columns: []string{readingreminder.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{readingreminder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReadingReminderUpdateOne is the builder for updating a single ReadingReminder entity.
type ReadingReminderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReadingReminderMutation
}

// SetReminderTime sets the "reminder_time" field.
func (_u *ReadingReminderUpdateOne) SetReminderTime(v string) *ReadingReminderUpdateOne {
	_u.mutation.SetReminderTime(v)
	return _u
}

// SetNillableReminderTime sets the "reminder_time" field if the given value is not nil.
func (_u *ReadingReminderUpdateOne) SetNillableReminderTime(v *string) *ReadingReminderUpdateOne {
	if v != nil {
		_u.SetReminderTime(*v)
	}
	return _u
}

// SetDayOfWeek sets the "day_of_week" field.
func (_u *ReadingReminderUpdateOne) SetDayOfWeek(v readingreminder.DayOfWeek) *ReadingReminderUpdateOne {
	_u.mutation.SetDayOfWeek(v)
	return _u
}

// SetNillableDayOfWeek sets the "day_of_week" field if the given value is not nil.
func (_u *ReadingReminderUpdateOne) SetNillableDayOfWeek(v *readingreminder.DayOfWeek) *ReadingReminderUpdateOne {
	if v != nil {
		_u.SetDayOfWeek(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *ReadingReminderUpdateOne) SetIsEnabled(v bool) *ReadingReminderUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *ReadingReminderUpdateOne) SetNillableIsEnabled(v *bool) *ReadingReminderUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ReadingReminderUpdateOne) SetMessage(v string) *ReadingReminderUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ReadingReminderUpdateOne) SetNillableMessage(v *string) *ReadingReminderUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReadingReminderUpdateOne) SetUpdatedAt(v time.Time) *ReadingReminderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ReadingReminderUpdateOne) SetOwnerID(id uuid.UUID) *ReadingReminderUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ReadingReminderUpdateOne) SetOwner(v *User) *ReadingReminderUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ReadingReminderMutation object of the builder.
func (_u *ReadingReminderUpdateOne) Mutation() *ReadingReminderMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ReadingReminderUpdateOne) ClearOwner() *ReadingReminderUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the ReadingReminderUpdate builder.
func (_u *ReadingReminderUpdateOne) Where(ps ...predicate.ReadingReminder) *ReadingReminderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReadingReminderUpdateOne) Select(field string, fields ...string) *ReadingReminderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReadingReminder entity.
func (_u *ReadingReminderUpdateOne) Save(ctx context.Context) (*ReadingReminder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReadingReminderUpdateOne) SaveX(ctx context.Context) *ReadingReminder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReadingReminderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReadingReminderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReadingReminderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := readingreminder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReadingReminderUpdateOne) check() error {
	if v, ok := _u.mutation.ReminderTime(); ok {
		if err := readingreminder.ReminderTimeValidator(v); err != nil {
			return &ValidationError{Name: "reminder_time", err: fmt.Errorf(`ent: validator failed for field "ReadingReminder.reminder_time": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DayOfWeek(); ok {
		if err := readingreminder.DayOfWeekValidator(v); err != nil {
			return &ValidationError{Name: "day_of_week", err: fmt.Errorf(`ent: validator failed for field "ReadingReminder.day_of_week": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReadingReminder.owner"`)
	}
	return nil
}

func (_u *ReadingReminderUpdateOne) sqlSave(ctx context.Context) (_node *ReadingReminder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(readingreminder.Table, readingreminder.Columns, sqlgraph.NewFieldSpec(readingreminder.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReadingReminder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, readingreminder.FieldID)
		for _, f := range fields {
			if !readingreminder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != readingreminder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReminderTime(); ok {
		_spec.SetField(readingreminder.FieldReminderTime, field.TypeString, value)
	}
	if value, ok := _u.mutation.DayOfWeek(); ok {
		_spec.SetField(readingreminder.FieldDayOfWeek, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(readingreminder.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(readingreminder.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(readingreminder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   readingreminder.OwnerTable,
			Columns: []string{readingreminder.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   readingreminder.OwnerTable,
			Columns: []string{readingreminder.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReadingReminder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{readingreminder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
