// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/home-library-backend/lib/ent/predicate"
	"github.com/dev-hyunsang/home-library-backend/lib/ent/readingreminder"
	"github.com/dev-hyunsang/home-library-backend/lib/ent/user"
	"github.com/google/uuid"
)

// ReadingReminderQuery is the builder for querying ReadingReminder entities.
type ReadingReminderQuery struct {
	config
	ctx        *QueryContext
	order      []readingreminder.OrderOption
	inters     []Interceptor
	predicates []predicate.ReadingReminder
	withOwner  *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReadingReminderQuery builder.
func (rrq *ReadingReminderQuery) Where(ps ...predicate.ReadingReminder) *ReadingReminderQuery {
	rrq.predicates = append(rrq.predicates, ps...)
	return rrq
}

// Limit the number of records to be returned by this query.
func (rrq *ReadingReminderQuery) Limit(limit int) *ReadingReminderQuery {
	rrq.ctx.Limit = &limit
	return rrq
}

// Offset to start from.
func (rrq *ReadingReminderQuery) Offset(offset int) *ReadingReminderQuery {
	rrq.ctx.Offset = &offset
	return rrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rrq *ReadingReminderQuery) Unique(unique bool) *ReadingReminderQuery {
	rrq.ctx.Unique = &unique
	return rrq
}

// Order specifies how the records should be ordered.
func (rrq *ReadingReminderQuery) Order(o ...readingreminder.OrderOption) *ReadingReminderQuery {
	rrq.order = append(rrq.order, o...)
	return rrq
}

// QueryOwner chains the current query on the "owner" edge.
func (rrq *ReadingReminderQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: rrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(readingreminder.Table, readingreminder.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, readingreminder.OwnerTable, readingreminder.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(rrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ReadingReminder entity from the query.
// Returns a *NotFoundError when no ReadingReminder was found.
func (rrq *ReadingReminderQuery) First(ctx context.Context) (*ReadingReminder, error) {
	nodes, err := rrq.Limit(1).All(setContextOp(ctx, rrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{readingreminder.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rrq *ReadingReminderQuery) FirstX(ctx context.Context) *ReadingReminder {
	node, err := rrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReadingReminder ID from the query.
// Returns a *NotFoundError when no ReadingReminder ID was found.
func (rrq *ReadingReminderQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rrq.Limit(1).IDs(setContextOp(ctx, rrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{readingreminder.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rrq *ReadingReminderQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := rrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReadingReminder entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReadingReminder entity is found.
// Returns a *NotFoundError when no ReadingReminder entities are found.
func (rrq *ReadingReminderQuery) Only(ctx context.Context) (*ReadingReminder, error) {
	nodes, err := rrq.Limit(2).All(setContextOp(ctx, rrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{readingreminder.Label}
	default:
		return nil, &NotSingularError{readingreminder.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rrq *ReadingReminderQuery) OnlyX(ctx context.Context) *ReadingReminder {
	node, err := rrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReadingReminder ID in the query.
// Returns a *NotSingularError when more than one ReadingReminder ID is found.
// Returns a *NotFoundError when no entities are found.
func (rrq *ReadingReminderQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rrq.Limit(2).IDs(setContextOp(ctx, rrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{readingreminder.Label}
	default:
		err = &NotSingularError{readingreminder.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rrq *ReadingReminderQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := rrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReadingReminders.
func (rrq *ReadingReminderQuery) All(ctx context.Context) ([]*ReadingReminder, error) {
	ctx = setContextOp(ctx, rrq.ctx, ent.OpQueryAll)
	if err := rrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReadingReminder, *ReadingReminderQuery]()
	return withInterceptors[[]*ReadingReminder](ctx, rrq, qr, rrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rrq *ReadingReminderQuery) AllX(ctx context.Context) []*ReadingReminder {
	nodes, err := rrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReadingReminder IDs.
func (rrq *ReadingReminderQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if rrq.ctx.Unique == nil && rrq.path != nil {
		rrq.Unique(true)
	}
	ctx = setContextOp(ctx, rrq.ctx, ent.OpQueryIDs)
	if err = rrq.Select(readingreminder.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rrq *ReadingReminderQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := rrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rrq *ReadingReminderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rrq.ctx, ent.OpQueryCount)
	if err := rrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rrq, querierCount[*ReadingReminderQuery](), rrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rrq *ReadingReminderQuery) CountX(ctx context.Context) int {
	count, err := rrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rrq *ReadingReminderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rrq.ctx, ent.OpQueryExist)
	switch _, err := rrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rrq *ReadingReminderQuery) ExistX(ctx context.Context) bool {
	exist, err := rrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReadingReminderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rrq *ReadingReminderQuery) Clone() *ReadingReminderQuery {
	if rrq == nil {
		return nil
	}
	return &ReadingReminderQuery{
		config:     rrq.config,
		ctx:        rrq.ctx.Clone(),
		order:      append([]readingreminder.OrderOption{}, rrq.order...),
		inters:     append([]Interceptor{}, rrq.inters...),
		predicates: append([]predicate.ReadingReminder{}, rrq.predicates...),
		withOwner:  rrq.withOwner.Clone(),
		// clone intermediate query.
		sql:  rrq.sql.Clone(),
		path: rrq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (rrq *ReadingReminderQuery) WithOwner(opts ...func(*UserQuery)) *ReadingReminderQuery {
	query := (&UserClient{config: rrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rrq.withOwner = query
	return rrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ReminderTime string `json:"reminder_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReadingReminder.Query().
//		GroupBy(readingreminder.FieldReminderTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rrq *ReadingReminderQuery) GroupBy(field string, fields ...string) *ReadingReminderGroupBy {
	rrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReadingReminderGroupBy{build: rrq}
	grbuild.flds = &rrq.ctx.Fields
	grbuild.label = readingreminder.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ReminderTime string `json:"reminder_time,omitempty"`
//	}
//
//	client.ReadingReminder.Query().
//		Select(readingreminder.FieldReminderTime).
//		Scan(ctx, &v)
func (rrq *ReadingReminderQuery) Select(fields ...string) *ReadingReminderSelect {
	rrq.ctx.Fields = append(rrq.ctx.Fields, fields...)
	sbuild := &ReadingReminderSelect{ReadingReminderQuery: rrq}
	sbuild.label = readingreminder.Label
	sbuild.flds, sbuild.scan = &rrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReadingReminderSelect configured with the given aggregations.
func (rrq *ReadingReminderQuery) Aggregate(fns ...AggregateFunc) *ReadingReminderSelect {
	return rrq.Select().Aggregate(fns...)
}

func (rrq *ReadingReminderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rrq); err != nil {
				return err
			}
		}
	}
	for _, f := range rrq.ctx.Fields {
		if !readingreminder.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rrq.path != nil {
		prev, err := rrq.path(ctx)
		if err != nil {
			return err
		}
		rrq.sql = prev
	}
	return nil
}

func (rrq *ReadingReminderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReadingReminder, error) {
	var (
		nodes       = []*ReadingReminder{}
		withFKs     = rrq.withFKs
		_spec       = rrq.querySpec()
		loadedTypes = [1]bool{
			rrq.withOwner != nil,
		}
	)
	if rrq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, readingreminder.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReadingReminder).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReadingReminder{config: rrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rrq.withOwner; query != nil {
		if err := rrq.loadOwner(ctx, query, nodes, nil,
			func(n *ReadingReminder, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rrq *ReadingReminderQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*ReadingReminder, init func(*ReadingReminder), assign func(*ReadingReminder, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ReadingReminder)
	for i := range nodes {
		if nodes[i].user_reading_reminders == nil {
			continue
		}
		fk := *nodes[i].user_reading_reminders
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_reading_reminders" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rrq *ReadingReminderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rrq.querySpec()
	_spec.Node.Columns = rrq.ctx.Fields
	if len(rrq.ctx.Fields) > 0 {
		_spec.Unique = rrq.ctx.Unique != nil && *rrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rrq.driver, _spec)
}

func (rrq *ReadingReminderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(readingreminder.Table, readingreminder.Columns, sqlgraph.NewFieldSpec(readingreminder.FieldID, field.TypeUUID))
	_spec.From = rrq.sql
	if unique := rrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rrq.path != nil {
		_spec.Unique = true
	}
	if fields := rrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, readingreminder.FieldID)
		for i := range fields {
			if fields[i] != readingreminder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rrq *ReadingReminderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rrq.driver.Dialect())
	t1 := builder.Table(readingreminder.Table)
	columns := rrq.ctx.Fields
	if len(columns) == 0 {
		columns = readingreminder.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rrq.sql != nil {
		selector = rrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rrq.ctx.Unique != nil && *rrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rrq.predicates {
		p(selector)
	}
	for _, p := range rrq.order {
		p(selector)
	}
	if offset := rrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReadingReminderGroupBy is the group-by builder for ReadingReminder entities.
type ReadingReminderGroupBy struct {
	selector
	build *ReadingReminderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rrgb *ReadingReminderGroupBy) Aggregate(fns ...AggregateFunc) *ReadingReminderGroupBy {
	rrgb.fns = append(rrgb.fns, fns...)
	return rrgb
}

// Scan applies the selector query and scans the result into the given value.
func (rrgb *ReadingReminderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rrgb.build.ctx, ent.OpQueryGroupBy)
	if err := rrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReadingReminderQuery, *ReadingReminderGroupBy](ctx, rrgb.build, rrgb, rrgb.build.inters, v)
}

func (rrgb *ReadingReminderGroupBy) sqlScan(ctx context.Context, root *ReadingReminderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rrgb.fns))
	for _, fn := range rrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rrgb.flds)+len(rrgb.fns))
		for _, f := range *rrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReadingReminderSelect is the builder for selecting fields of ReadingReminder entities.
type ReadingReminderSelect struct {
	*ReadingReminderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rrs *ReadingReminderSelect) Aggregate(fns ...AggregateFunc) *ReadingReminderSelect {
	rrs.fns = append(rrs.fns, fns...)
	return rrs
}

// Scan applies the selector query and scans the result into the given value.
func (rrs *ReadingReminderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rrs.ctx, ent.OpQuerySelect)
	if err := rrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReadingReminderQuery, *ReadingReminderSelect](ctx, rrs.ReadingReminderQuery, rrs, rrs.inters, v)
}

func (rrs *ReadingReminderSelect) sqlScan(ctx context.Context, root *ReadingReminderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rrs.fns))
	for _, fn := range rrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
