// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/predicate"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/readingreminder"
)

// ReadingReminderDelete is the builder for deleting a ReadingReminder entity.
type ReadingReminderDelete struct {
	config
	hooks    []Hook
	mutation *ReadingReminderMutation
}

// Where appends a list predicates to the ReadingReminderDelete builder.
func (_d *ReadingReminderDelete) Where(ps ...predicate.ReadingReminder) *ReadingReminderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ReadingReminderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReadingReminderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ReadingReminderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(readingreminder.Table, sqlgraph.NewFieldSpec(readingreminder.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ReadingReminderDeleteOne is the builder for deleting a single ReadingReminder entity.
type ReadingReminderDeleteOne struct {
	_d *ReadingReminderDelete
}

// Where appends a list predicates to the ReadingReminderDelete builder.
func (_d *ReadingReminderDeleteOne) Where(ps ...predicate.ReadingReminder) *ReadingReminderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ReadingReminderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{readingreminder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReadingReminderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
