// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dev-hyunsang/home-library-backend/lib/ent/readingreminder"
	"github.com/dev-hyunsang/home-library-backend/lib/ent/user"
	"github.com/google/uuid"
)

// ReadingReminder is the model entity for the ReadingReminder schema.
type ReadingReminder struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// 알림 시간 (HH:MM 형식)
	ReminderTime string `json:"reminder_time,omitempty"`
	// 알림 요일
	DayOfWeek readingreminder.DayOfWeek `json:"day_of_week,omitempty"`
	// 알림 활성화 여부
	IsEnabled bool `json:"is_enabled,omitempty"`
	// 알림 메시지
	Message string `json:"message,omitempty"`
	// 생성 시간
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 수정 시간
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReadingReminderQuery when eager-loading is set.
	Edges                  ReadingReminderEdges `json:"edges"`
	user_reading_reminders *uuid.UUID
	selectValues           sql.SelectValues
}

// ReadingReminderEdges holds the relations/edges for other nodes in the graph.
type ReadingReminderEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReadingReminderEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReadingReminder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case readingreminder.FieldIsEnabled:
			values[i] = new(sql.NullBool)
		case readingreminder.FieldReminderTime, readingreminder.FieldDayOfWeek, readingreminder.FieldMessage:
			values[i] = new(sql.NullString)
		case readingreminder.FieldCreatedAt, readingreminder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case readingreminder.FieldID:
			values[i] = new(uuid.UUID)
		case readingreminder.ForeignKeys[0]: // user_reading_reminders
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReadingReminder fields.
func (rr *ReadingReminder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case readingreminder.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				rr.ID = *value
			}
		case readingreminder.FieldReminderTime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reminder_time", values[i])
			} else if value.Valid {
				rr.ReminderTime = value.String
			}
		case readingreminder.FieldDayOfWeek:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field day_of_week", values[i])
			} else if value.Valid {
				rr.DayOfWeek = readingreminder.DayOfWeek(value.String)
			}
		case readingreminder.FieldIsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enabled", values[i])
			} else if value.Valid {
				rr.IsEnabled = value.Bool
			}
		case readingreminder.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				rr.Message = value.String
			}
		case readingreminder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rr.CreatedAt = value.Time
			}
		case readingreminder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				rr.UpdatedAt = value.Time
			}
		case readingreminder.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_reading_reminders", values[i])
			} else if value.Valid {
				rr.user_reading_reminders = new(uuid.UUID)
				*rr.user_reading_reminders = *value.S.(*uuid.UUID)
			}
		default:
			rr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReadingReminder.
// This includes values selected through modifiers, order, etc.
func (rr *ReadingReminder) Value(name string) (ent.Value, error) {
	return rr.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the ReadingReminder entity.
func (rr *ReadingReminder) QueryOwner() *UserQuery {
	return NewReadingReminderClient(rr.config).QueryOwner(rr)
}

// Update returns a builder for updating this ReadingReminder.
// Note that you need to call ReadingReminder.Unwrap() before calling this method if this ReadingReminder
// was returned from a transaction, and the transaction was committed or rolled back.
func (rr *ReadingReminder) Update() *ReadingReminderUpdateOne {
	return NewReadingReminderClient(rr.config).UpdateOne(rr)
}

// Unwrap unwraps the ReadingReminder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rr *ReadingReminder) Unwrap() *ReadingReminder {
	_tx, ok := rr.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReadingReminder is not a transactional entity")
	}
	rr.config.driver = _tx.drv
	return rr
}

// String implements the fmt.Stringer.
func (rr *ReadingReminder) String() string {
	var builder strings.Builder
	builder.WriteString("ReadingReminder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rr.ID))
	builder.WriteString("reminder_time=")
	builder.WriteString(rr.ReminderTime)
	builder.WriteString(", ")
	builder.WriteString("day_of_week=")
	builder.WriteString(fmt.Sprintf("%v", rr.DayOfWeek))
	builder.WriteString(", ")
	builder.WriteString("is_enabled=")
	builder.WriteString(fmt.Sprintf("%v", rr.IsEnabled))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(rr.Message)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(rr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(rr.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReadingReminders is a parsable slice of ReadingReminder.
type ReadingReminders []*ReadingReminder
