// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/home-library-backend/lib/ent/book"
	"github.com/dev-hyunsang/home-library-backend/lib/ent/predicate"
	"github.com/dev-hyunsang/home-library-backend/lib/ent/review"
	"github.com/dev-hyunsang/home-library-backend/lib/ent/user"
	"github.com/google/uuid"
)

// ReviewUpdate is the builder for updating Review entities.
type ReviewUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewMutation
}

// Where appends a list predicates to the ReviewUpdate builder.
func (ru *ReviewUpdate) Where(ps ...predicate.Review) *ReviewUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetBookIsbn sets the "book_isbn" field.
func (ru *ReviewUpdate) SetBookIsbn(s string) *ReviewUpdate {
	ru.mutation.SetBookIsbn(s)
	return ru
}

// SetNillableBookIsbn sets the "book_isbn" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableBookIsbn(s *string) *ReviewUpdate {
	if s != nil {
		ru.SetBookIsbn(*s)
	}
	return ru
}

// SetContent sets the "content" field.
func (ru *ReviewUpdate) SetContent(s string) *ReviewUpdate {
	ru.mutation.SetContent(s)
	return ru
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableContent(s *string) *ReviewUpdate {
	if s != nil {
		ru.SetContent(*s)
	}
	return ru
}

// SetRating sets the "rating" field.
func (ru *ReviewUpdate) SetRating(i int) *ReviewUpdate {
	ru.mutation.ResetRating()
	ru.mutation.SetRating(i)
	return ru
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableRating(i *int) *ReviewUpdate {
	if i != nil {
		ru.SetRating(*i)
	}
	return ru
}

// AddRating adds i to the "rating" field.
func (ru *ReviewUpdate) AddRating(i int) *ReviewUpdate {
	ru.mutation.AddRating(i)
	return ru
}

// SetIsPublic sets the "is_public" field.
func (ru *ReviewUpdate) SetIsPublic(b bool) *ReviewUpdate {
	ru.mutation.SetIsPublic(b)
	return ru
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableIsPublic(b *bool) *ReviewUpdate {
	if b != nil {
		ru.SetIsPublic(*b)
	}
	return ru
}

// SetUpdatedAt sets the "updated_at" field.
func (ru *ReviewUpdate) SetUpdatedAt(t time.Time) *ReviewUpdate {
	ru.mutation.SetUpdatedAt(t)
	return ru
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (ru *ReviewUpdate) SetOwnerID(id uuid.UUID) *ReviewUpdate {
	ru.mutation.SetOwnerID(id)
	return ru
}

// SetOwner sets the "owner" edge to the User entity.
func (ru *ReviewUpdate) SetOwner(u *User) *ReviewUpdate {
	return ru.SetOwnerID(u.ID)
}

// SetBookID sets the "book" edge to the Book entity by ID.
func (ru *ReviewUpdate) SetBookID(id uuid.UUID) *ReviewUpdate {
	ru.mutation.SetBookID(id)
	return ru
}

// SetNillableBookID sets the "book" edge to the Book entity by ID if the given value is not nil.
func (ru *ReviewUpdate) SetNillableBookID(id *uuid.UUID) *ReviewUpdate {
	if id != nil {
		ru = ru.SetBookID(*id)
	}
	return ru
}

// SetBook sets the "book" edge to the Book entity.
func (ru *ReviewUpdate) SetBook(b *Book) *ReviewUpdate {
	return ru.SetBookID(b.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (ru *ReviewUpdate) Mutation() *ReviewMutation {
	return ru.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (ru *ReviewUpdate) ClearOwner() *ReviewUpdate {
	ru.mutation.ClearOwner()
	return ru
}

// ClearBook clears the "book" edge to the Book entity.
func (ru *ReviewUpdate) ClearBook() *ReviewUpdate {
	ru.mutation.ClearBook()
	return ru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *ReviewUpdate) Save(ctx context.Context) (int, error) {
	ru.defaults()
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *ReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *ReviewUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *ReviewUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ru *ReviewUpdate) defaults() {
	if _, ok := ru.mutation.UpdatedAt(); !ok {
		v := review.UpdateDefaultUpdatedAt()
		ru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *ReviewUpdate) check() error {
	if v, ok := ru.mutation.BookIsbn(); ok {
		if err := review.BookIsbnValidator(v); err != nil {
			return &ValidationError{Name: "book_isbn", err: fmt.Errorf(`ent: validator failed for field "Review.book_isbn": %w`, err)}
		}
	}
	if v, ok := ru.mutation.Content(); ok {
		if err := review.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Review.content": %w`, err)}
		}
	}
	if v, ok := ru.mutation.Rating(); ok {
		if err := review.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Review.rating": %w`, err)}
		}
	}
	if ru.mutation.OwnerCleared() && len(ru.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Review.owner"`)
	}
	return nil
}

func (ru *ReviewUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.BookIsbn(); ok {
		_spec.SetField(review.FieldBookIsbn, field.TypeString, value)
	}
	if value, ok := ru.mutation.Content(); ok {
		_spec.SetField(review.FieldContent, field.TypeString, value)
	}
	if value, ok := ru.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := ru.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := ru.mutation.IsPublic(); ok {
		_spec.SetField(review.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := ru.mutation.UpdatedAt(); ok {
		_spec.SetField(review.FieldUpdatedAt, field.TypeTime, value)
	}
	if ru.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.OwnerTable,
			Columns: []string{review.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.OwnerTable,
			Columns: []string{review.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.BookTable,
			Columns: []string{review.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.BookTable,
			Columns: []string{review.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// ReviewUpdateOne is the builder for updating a single Review entity.
type ReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewMutation
}

// SetBookIsbn sets the "book_isbn" field.
func (ruo *ReviewUpdateOne) SetBookIsbn(s string) *ReviewUpdateOne {
	ruo.mutation.SetBookIsbn(s)
	return ruo
}

// SetNillableBookIsbn sets the "book_isbn" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableBookIsbn(s *string) *ReviewUpdateOne {
	if s != nil {
		ruo.SetBookIsbn(*s)
	}
	return ruo
}

// SetContent sets the "content" field.
func (ruo *ReviewUpdateOne) SetContent(s string) *ReviewUpdateOne {
	ruo.mutation.SetContent(s)
	return ruo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableContent(s *string) *ReviewUpdateOne {
	if s != nil {
		ruo.SetContent(*s)
	}
	return ruo
}

// SetRating sets the "rating" field.
func (ruo *ReviewUpdateOne) SetRating(i int) *ReviewUpdateOne {
	ruo.mutation.ResetRating()
	ruo.mutation.SetRating(i)
	return ruo
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableRating(i *int) *ReviewUpdateOne {
	if i != nil {
		ruo.SetRating(*i)
	}
	return ruo
}

// AddRating adds i to the "rating" field.
func (ruo *ReviewUpdateOne) AddRating(i int) *ReviewUpdateOne {
	ruo.mutation.AddRating(i)
	return ruo
}

// SetIsPublic sets the "is_public" field.
func (ruo *ReviewUpdateOne) SetIsPublic(b bool) *ReviewUpdateOne {
	ruo.mutation.SetIsPublic(b)
	return ruo
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableIsPublic(b *bool) *ReviewUpdateOne {
	if b != nil {
		ruo.SetIsPublic(*b)
	}
	return ruo
}

// SetUpdatedAt sets the "updated_at" field.
func (ruo *ReviewUpdateOne) SetUpdatedAt(t time.Time) *ReviewUpdateOne {
	ruo.mutation.SetUpdatedAt(t)
	return ruo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (ruo *ReviewUpdateOne) SetOwnerID(id uuid.UUID) *ReviewUpdateOne {
	ruo.mutation.SetOwnerID(id)
	return ruo
}

// SetOwner sets the "owner" edge to the User entity.
func (ruo *ReviewUpdateOne) SetOwner(u *User) *ReviewUpdateOne {
	return ruo.SetOwnerID(u.ID)
}

// SetBookID sets the "book" edge to the Book entity by ID.
func (ruo *ReviewUpdateOne) SetBookID(id uuid.UUID) *ReviewUpdateOne {
	ruo.mutation.SetBookID(id)
	return ruo
}

// SetNillableBookID sets the "book" edge to the Book entity by ID if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableBookID(id *uuid.UUID) *ReviewUpdateOne {
	if id != nil {
		ruo = ruo.SetBookID(*id)
	}
	return ruo
}

// SetBook sets the "book" edge to the Book entity.
func (ruo *ReviewUpdateOne) SetBook(b *Book) *ReviewUpdateOne {
	return ruo.SetBookID(b.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (ruo *ReviewUpdateOne) Mutation() *ReviewMutation {
	return ruo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (ruo *ReviewUpdateOne) ClearOwner() *ReviewUpdateOne {
	ruo.mutation.ClearOwner()
	return ruo
}

// ClearBook clears the "book" edge to the Book entity.
func (ruo *ReviewUpdateOne) ClearBook() *ReviewUpdateOne {
	ruo.mutation.ClearBook()
	return ruo
}

// Where appends a list predicates to the ReviewUpdate builder.
func (ruo *ReviewUpdateOne) Where(ps ...predicate.Review) *ReviewUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *ReviewUpdateOne) Select(field string, fields ...string) *ReviewUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Review entity.
func (ruo *ReviewUpdateOne) Save(ctx context.Context) (*Review, error) {
	ruo.defaults()
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *ReviewUpdateOne) SaveX(ctx context.Context) *Review {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *ReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *ReviewUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ruo *ReviewUpdateOne) defaults() {
	if _, ok := ruo.mutation.UpdatedAt(); !ok {
		v := review.UpdateDefaultUpdatedAt()
		ruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *ReviewUpdateOne) check() error {
	if v, ok := ruo.mutation.BookIsbn(); ok {
		if err := review.BookIsbnValidator(v); err != nil {
			return &ValidationError{Name: "book_isbn", err: fmt.Errorf(`ent: validator failed for field "Review.book_isbn": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.Content(); ok {
		if err := review.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Review.content": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.Rating(); ok {
		if err := review.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Review.rating": %w`, err)}
		}
	}
	if ruo.mutation.OwnerCleared() && len(ruo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Review.owner"`)
	}
	return nil
}

func (ruo *ReviewUpdateOne) sqlSave(ctx context.Context) (_node *Review, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Review.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, review.FieldID)
		for _, f := range fields {
			if !review.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != review.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.BookIsbn(); ok {
		_spec.SetField(review.FieldBookIsbn, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Content(); ok {
		_spec.SetField(review.FieldContent, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.IsPublic(); ok {
		_spec.SetField(review.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := ruo.mutation.UpdatedAt(); ok {
		_spec.SetField(review.FieldUpdatedAt, field.TypeTime, value)
	}
	if ruo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.OwnerTable,
			Columns: []string{review.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.OwnerTable,
			Columns: []string{review.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.BookTable,
			Columns: []string{review.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.BookTable,
			Columns: []string{review.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Review{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
