// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/dev-hyunsang/home-library/lib/ent/adminapikey"
	"github.com/dev-hyunsang/home-library/lib/ent/book"
	"github.com/dev-hyunsang/home-library/lib/ent/bookmark"
	"github.com/dev-hyunsang/home-library/lib/ent/emailverification"
	"github.com/dev-hyunsang/home-library/lib/ent/readingreminder"
	"github.com/dev-hyunsang/home-library/lib/ent/review"
	"github.com/dev-hyunsang/home-library/lib/ent/schema"
	"github.com/dev-hyunsang/home-library/lib/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminapikeyFields := schema.AdminAPIKey{}.Fields()
	_ = adminapikeyFields
	// adminapikeyDescName is the schema descriptor for name field.
	adminapikeyDescName := adminapikeyFields[1].Descriptor()
	// adminapikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	adminapikey.NameValidator = adminapikeyDescName.Validators[0].(func(string) error)
	// adminapikeyDescKeyHash is the schema descriptor for key_hash field.
	adminapikeyDescKeyHash := adminapikeyFields[2].Descriptor()
	// adminapikey.KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	adminapikey.KeyHashValidator = adminapikeyDescKeyHash.Validators[0].(func(string) error)
	// adminapikeyDescKeyPrefix is the schema descriptor for key_prefix field.
	adminapikeyDescKeyPrefix := adminapikeyFields[3].Descriptor()
	// adminapikey.KeyPrefixValidator is a validator for the "key_prefix" field. It is called by the builders before save.
	adminapikey.KeyPrefixValidator = adminapikeyDescKeyPrefix.Validators[0].(func(string) error)
	// adminapikeyDescIsActive is the schema descriptor for is_active field.
	adminapikeyDescIsActive := adminapikeyFields[4].Descriptor()
	// adminapikey.DefaultIsActive holds the default value on creation for the is_active field.
	adminapikey.DefaultIsActive = adminapikeyDescIsActive.Default.(bool)
	// adminapikeyDescCreatedAt is the schema descriptor for created_at field.
	adminapikeyDescCreatedAt := adminapikeyFields[7].Descriptor()
	// adminapikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminapikey.DefaultCreatedAt = adminapikeyDescCreatedAt.Default.(func() time.Time)
	// adminapikeyDescUpdatedAt is the schema descriptor for updated_at field.
	adminapikeyDescUpdatedAt := adminapikeyFields[8].Descriptor()
	// adminapikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	adminapikey.DefaultUpdatedAt = adminapikeyDescUpdatedAt.Default.(func() time.Time)
	// adminapikey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminapikey.UpdateDefaultUpdatedAt = adminapikeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescBookTitle is the schema descriptor for book_title field.
	bookDescBookTitle := bookFields[1].Descriptor()
	// book.BookTitleValidator is a validator for the "book_title" field. It is called by the builders before save.
	book.BookTitleValidator = bookDescBookTitle.Validators[0].(func(string) error)
	// bookDescAuthor is the schema descriptor for author field.
	bookDescAuthor := bookFields[2].Descriptor()
	// book.AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	book.AuthorValidator = bookDescAuthor.Validators[0].(func(string) error)
	// bookDescStatus is the schema descriptor for status field.
	bookDescStatus := bookFields[5].Descriptor()
	// book.DefaultStatus holds the default value on creation for the status field.
	book.DefaultStatus = bookDescStatus.Default.(int)
	// bookDescCreatedAt is the schema descriptor for created_at field.
	bookDescCreatedAt := bookFields[6].Descriptor()
	// book.DefaultCreatedAt holds the default value on creation for the created_at field.
	book.DefaultCreatedAt = bookDescCreatedAt.Default.(time.Time)
	// bookDescUpdatedAt is the schema descriptor for updated_at field.
	bookDescUpdatedAt := bookFields[7].Descriptor()
	// book.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	book.DefaultUpdatedAt = bookDescUpdatedAt.Default.(time.Time)
	// book.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	book.UpdateDefaultUpdatedAt = bookDescUpdatedAt.UpdateDefault.(func() time.Time)
	bookmarkFields := schema.Bookmark{}.Fields()
	_ = bookmarkFields
	// bookmarkDescCreatedAt is the schema descriptor for created_at field.
	bookmarkDescCreatedAt := bookmarkFields[1].Descriptor()
	// bookmark.DefaultCreatedAt holds the default value on creation for the created_at field.
	bookmark.DefaultCreatedAt = bookmarkDescCreatedAt.Default.(func() time.Time)
	// bookmarkDescID is the schema descriptor for id field.
	bookmarkDescID := bookmarkFields[0].Descriptor()
	// bookmark.DefaultID holds the default value on creation for the id field.
	bookmark.DefaultID = bookmarkDescID.Default.(func() uuid.UUID)
	emailverificationFields := schema.EmailVerification{}.Fields()
	_ = emailverificationFields
	// emailverificationDescEmail is the schema descriptor for email field.
	emailverificationDescEmail := emailverificationFields[1].Descriptor()
	// emailverification.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	emailverification.EmailValidator = emailverificationDescEmail.Validators[0].(func(string) error)
	// emailverificationDescCode is the schema descriptor for code field.
	emailverificationDescCode := emailverificationFields[2].Descriptor()
	// emailverification.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	emailverification.CodeValidator = func() func(string) error {
		validators := emailverificationDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// emailverificationDescIsVerified is the schema descriptor for is_verified field.
	emailverificationDescIsVerified := emailverificationFields[4].Descriptor()
	// emailverification.DefaultIsVerified holds the default value on creation for the is_verified field.
	emailverification.DefaultIsVerified = emailverificationDescIsVerified.Default.(bool)
	// emailverificationDescCreatedAt is the schema descriptor for created_at field.
	emailverificationDescCreatedAt := emailverificationFields[5].Descriptor()
	// emailverification.DefaultCreatedAt holds the default value on creation for the created_at field.
	emailverification.DefaultCreatedAt = emailverificationDescCreatedAt.Default.(func() time.Time)
	readingreminderFields := schema.ReadingReminder{}.Fields()
	_ = readingreminderFields
	// readingreminderDescReminderTime is the schema descriptor for reminder_time field.
	readingreminderDescReminderTime := readingreminderFields[1].Descriptor()
	// readingreminder.ReminderTimeValidator is a validator for the "reminder_time" field. It is called by the builders before save.
	readingreminder.ReminderTimeValidator = readingreminderDescReminderTime.Validators[0].(func(string) error)
	// readingreminderDescIsEnabled is the schema descriptor for is_enabled field.
	readingreminderDescIsEnabled := readingreminderFields[3].Descriptor()
	// readingreminder.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	readingreminder.DefaultIsEnabled = readingreminderDescIsEnabled.Default.(bool)
	// readingreminderDescMessage is the schema descriptor for message field.
	readingreminderDescMessage := readingreminderFields[4].Descriptor()
	// readingreminder.DefaultMessage holds the default value on creation for the message field.
	readingreminder.DefaultMessage = readingreminderDescMessage.Default.(string)
	// readingreminderDescCreatedAt is the schema descriptor for created_at field.
	readingreminderDescCreatedAt := readingreminderFields[5].Descriptor()
	// readingreminder.DefaultCreatedAt holds the default value on creation for the created_at field.
	readingreminder.DefaultCreatedAt = readingreminderDescCreatedAt.Default.(func() time.Time)
	// readingreminderDescUpdatedAt is the schema descriptor for updated_at field.
	readingreminderDescUpdatedAt := readingreminderFields[6].Descriptor()
	// readingreminder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	readingreminder.DefaultUpdatedAt = readingreminderDescUpdatedAt.Default.(func() time.Time)
	// readingreminder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	readingreminder.UpdateDefaultUpdatedAt = readingreminderDescUpdatedAt.UpdateDefault.(func() time.Time)
	reviewFields := schema.Review{}.Fields()
	_ = reviewFields
	// reviewDescContent is the schema descriptor for content field.
	reviewDescContent := reviewFields[1].Descriptor()
	// review.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	review.ContentValidator = reviewDescContent.Validators[0].(func(string) error)
	// reviewDescRating is the schema descriptor for rating field.
	reviewDescRating := reviewFields[2].Descriptor()
	// review.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	review.RatingValidator = func() func(int) error {
		validators := reviewDescRating.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(rating int) error {
			for _, fn := range fns {
				if err := fn(rating); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// reviewDescIsPublic is the schema descriptor for is_public field.
	reviewDescIsPublic := reviewFields[3].Descriptor()
	// review.DefaultIsPublic holds the default value on creation for the is_public field.
	review.DefaultIsPublic = reviewDescIsPublic.Default.(bool)
	// reviewDescCreatedAt is the schema descriptor for created_at field.
	reviewDescCreatedAt := reviewFields[4].Descriptor()
	// review.DefaultCreatedAt holds the default value on creation for the created_at field.
	review.DefaultCreatedAt = reviewDescCreatedAt.Default.(func() time.Time)
	// reviewDescUpdatedAt is the schema descriptor for updated_at field.
	reviewDescUpdatedAt := reviewFields[5].Descriptor()
	// review.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	review.DefaultUpdatedAt = reviewDescUpdatedAt.Default.(func() time.Time)
	// review.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	review.UpdateDefaultUpdatedAt = reviewDescUpdatedAt.UpdateDefault.(func() time.Time)
	// reviewDescID is the schema descriptor for id field.
	reviewDescID := reviewFields[0].Descriptor()
	// review.DefaultID holds the default value on creation for the id field.
	review.DefaultID = reviewDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescNickName is the schema descriptor for nick_name field.
	userDescNickName := userFields[1].Descriptor()
	// user.NickNameValidator is a validator for the "nick_name" field. It is called by the builders before save.
	user.NickNameValidator = userDescNickName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescIsPublished is the schema descriptor for is_published field.
	userDescIsPublished := userFields[4].Descriptor()
	// user.DefaultIsPublished holds the default value on creation for the is_published field.
	user.DefaultIsPublished = userDescIsPublished.Default.(bool)
	// userDescIsTermsAgreed is the schema descriptor for is_terms_agreed field.
	userDescIsTermsAgreed := userFields[5].Descriptor()
	// user.DefaultIsTermsAgreed holds the default value on creation for the is_terms_agreed field.
	user.DefaultIsTermsAgreed = userDescIsTermsAgreed.Default.(bool)
	// userDescTimezone is the schema descriptor for timezone field.
	userDescTimezone := userFields[7].Descriptor()
	// user.DefaultTimezone holds the default value on creation for the timezone field.
	user.DefaultTimezone = userDescTimezone.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[8].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[9].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
}
