// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/book"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/bookmark"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/predicate"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/readingreminder"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/review"
	"github.com/dev-hyunsang/my-own-library-backend/lib/ent/user"
	"github.com/google/uuid"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNickName sets the "nick_name" field.
func (_u *UserUpdate) SetNickName(v string) *UserUpdate {
	_u.mutation.SetNickName(v)
	return _u
}

// SetNillableNickName sets the "nick_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableNickName(v *string) *UserUpdate {
	if v != nil {
		_u.SetNickName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdate) SetPassword(v string) *UserUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePassword(v *string) *UserUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *UserUpdate) ClearPassword() *UserUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetIsPublished sets the "is_published" field.
func (_u *UserUpdate) SetIsPublished(v bool) *UserUpdate {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsPublished(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// SetIsTermsAgreed sets the "is_terms_agreed" field.
func (_u *UserUpdate) SetIsTermsAgreed(v bool) *UserUpdate {
	_u.mutation.SetIsTermsAgreed(v)
	return _u
}

// SetNillableIsTermsAgreed sets the "is_terms_agreed" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsTermsAgreed(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsTermsAgreed(*v)
	}
	return _u
}

// SetIsPrivacyAgreed sets the "is_privacy_agreed" field.
func (_u *UserUpdate) SetIsPrivacyAgreed(v bool) *UserUpdate {
	_u.mutation.SetIsPrivacyAgreed(v)
	return _u
}

// SetNillableIsPrivacyAgreed sets the "is_privacy_agreed" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsPrivacyAgreed(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsPrivacyAgreed(*v)
	}
	return _u
}

// SetFcmToken sets the "fcm_token" field.
func (_u *UserUpdate) SetFcmToken(v string) *UserUpdate {
	_u.mutation.SetFcmToken(v)
	return _u
}

// SetNillableFcmToken sets the "fcm_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableFcmToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetFcmToken(*v)
	}
	return _u
}

// ClearFcmToken clears the value of the "fcm_token" field.
func (_u *UserUpdate) ClearFcmToken() *UserUpdate {
	_u.mutation.ClearFcmToken()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *UserUpdate) SetTimezone(v string) *UserUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTimezone(v *string) *UserUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUpdatedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (_u *UserUpdate) AddBookIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBooks adds the "books" edges to the Book entity.
func (_u *UserUpdate) AddBooks(v ...*Book) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (_u *UserUpdate) AddReviewIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the Review entity.
func (_u *UserUpdate) AddReviews(v ...*Review) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// AddBookmarkIDs adds the "bookmarks" edge to the Bookmark entity by IDs.
func (_u *UserUpdate) AddBookmarkIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddBookmarkIDs(ids...)
	return _u
}

// AddBookmarks adds the "bookmarks" edges to the Bookmark entity.
func (_u *UserUpdate) AddBookmarks(v ...*Bookmark) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookmarkIDs(ids...)
}

// AddReadingReminderIDs adds the "reading_reminders" edge to the ReadingReminder entity by IDs.
func (_u *UserUpdate) AddReadingReminderIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddReadingReminderIDs(ids...)
	return _u
}

// AddReadingReminders adds the "reading_reminders" edges to the ReadingReminder entity.
func (_u *UserUpdate) AddReadingReminders(v ...*ReadingReminder) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReadingReminderIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearBooks clears all "books" edges to the Book entity.
func (_u *UserUpdate) ClearBooks() *UserUpdate {
	_u.mutation.ClearBooks()
	return _u
}

// RemoveBookIDs removes the "books" edge to Book entities by IDs.
func (_u *UserUpdate) RemoveBookIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBooks removes "books" edges to Book entities.
func (_u *UserUpdate) RemoveBooks(v ...*Book) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (_u *UserUpdate) ClearReviews() *UserUpdate {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (_u *UserUpdate) RemoveReviewIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to Review entities.
func (_u *UserUpdate) RemoveReviews(v ...*Review) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// ClearBookmarks clears all "bookmarks" edges to the Bookmark entity.
func (_u *UserUpdate) ClearBookmarks() *UserUpdate {
	_u.mutation.ClearBookmarks()
	return _u
}

// RemoveBookmarkIDs removes the "bookmarks" edge to Bookmark entities by IDs.
func (_u *UserUpdate) RemoveBookmarkIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveBookmarkIDs(ids...)
	return _u
}

// RemoveBookmarks removes "bookmarks" edges to Bookmark entities.
func (_u *UserUpdate) RemoveBookmarks(v ...*Bookmark) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookmarkIDs(ids...)
}

// ClearReadingReminders clears all "reading_reminders" edges to the ReadingReminder entity.
func (_u *UserUpdate) ClearReadingReminders() *UserUpdate {
	_u.mutation.ClearReadingReminders()
	return _u
}

// RemoveReadingReminderIDs removes the "reading_reminders" edge to ReadingReminder entities by IDs.
func (_u *UserUpdate) RemoveReadingReminderIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveReadingReminderIDs(ids...)
	return _u
}

// RemoveReadingReminders removes "reading_reminders" edges to ReadingReminder entities.
func (_u *UserUpdate) RemoveReadingReminders(v ...*ReadingReminder) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReadingReminderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.NickName(); ok {
		if err := user.NickNameValidator(v); err != nil {
			return &ValidationError{Name: "nick_name", err: fmt.Errorf(`ent: validator failed for field "User.nick_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NickName(); ok {
		_spec.SetField(user.FieldNickName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(user.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(user.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsTermsAgreed(); ok {
		_spec.SetField(user.FieldIsTermsAgreed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPrivacyAgreed(); ok {
		_spec.SetField(user.FieldIsPrivacyAgreed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FcmToken(); ok {
		_spec.SetField(user.FieldFcmToken, field.TypeString, value)
	}
	if _u.mutation.FcmTokenCleared() {
		_spec.ClearField(user.FieldFcmToken, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(user.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BooksTable,
			Columns: []string{user.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBooksIDs(); len(nodes) > 0 && !_u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BooksTable,
			Columns: []string{user.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BooksTable,
			Columns: []string{user.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewsTable,
			Columns: []string{user.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewsTable,
			Columns: []string{user.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewsTable,
			Columns: []string{user.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookmarksTable,
			Columns: []string{user.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookmarksIDs(); len(nodes) > 0 && !_u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookmarksTable,
			Columns: []string{user.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookmarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookmarksTable,
			Columns: []string{user.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReadingRemindersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReadingRemindersTable,
			Columns: []string{user.ReadingRemindersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(readingreminder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReadingRemindersIDs(); len(nodes) > 0 && !_u.mutation.ReadingRemindersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReadingRemindersTable,
			Columns: []string{user.ReadingRemindersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(readingreminder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReadingRemindersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReadingRemindersTable,
			Columns: []string{user.ReadingRemindersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(readingreminder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetNickName sets the "nick_name" field.
func (_u *UserUpdateOne) SetNickName(v string) *UserUpdateOne {
	_u.mutation.SetNickName(v)
	return _u
}

// SetNillableNickName sets the "nick_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNickName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetNickName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdateOne) SetPassword(v string) *UserUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePassword(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *UserUpdateOne) ClearPassword() *UserUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetIsPublished sets the "is_published" field.
func (_u *UserUpdateOne) SetIsPublished(v bool) *UserUpdateOne {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsPublished(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// SetIsTermsAgreed sets the "is_terms_agreed" field.
func (_u *UserUpdateOne) SetIsTermsAgreed(v bool) *UserUpdateOne {
	_u.mutation.SetIsTermsAgreed(v)
	return _u
}

// SetNillableIsTermsAgreed sets the "is_terms_agreed" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsTermsAgreed(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsTermsAgreed(*v)
	}
	return _u
}

// SetIsPrivacyAgreed sets the "is_privacy_agreed" field.
func (_u *UserUpdateOne) SetIsPrivacyAgreed(v bool) *UserUpdateOne {
	_u.mutation.SetIsPrivacyAgreed(v)
	return _u
}

// SetNillableIsPrivacyAgreed sets the "is_privacy_agreed" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsPrivacyAgreed(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsPrivacyAgreed(*v)
	}
	return _u
}

// SetFcmToken sets the "fcm_token" field.
func (_u *UserUpdateOne) SetFcmToken(v string) *UserUpdateOne {
	_u.mutation.SetFcmToken(v)
	return _u
}

// SetNillableFcmToken sets the "fcm_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableFcmToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetFcmToken(*v)
	}
	return _u
}

// ClearFcmToken clears the value of the "fcm_token" field.
func (_u *UserUpdateOne) ClearFcmToken() *UserUpdateOne {
	_u.mutation.ClearFcmToken()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *UserUpdateOne) SetTimezone(v string) *UserUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTimezone(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUpdatedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (_u *UserUpdateOne) AddBookIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBooks adds the "books" edges to the Book entity.
func (_u *UserUpdateOne) AddBooks(v ...*Book) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (_u *UserUpdateOne) AddReviewIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the Review entity.
func (_u *UserUpdateOne) AddReviews(v ...*Review) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// AddBookmarkIDs adds the "bookmarks" edge to the Bookmark entity by IDs.
func (_u *UserUpdateOne) AddBookmarkIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddBookmarkIDs(ids...)
	return _u
}

// AddBookmarks adds the "bookmarks" edges to the Bookmark entity.
func (_u *UserUpdateOne) AddBookmarks(v ...*Bookmark) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookmarkIDs(ids...)
}

// AddReadingReminderIDs adds the "reading_reminders" edge to the ReadingReminder entity by IDs.
func (_u *UserUpdateOne) AddReadingReminderIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddReadingReminderIDs(ids...)
	return _u
}

// AddReadingReminders adds the "reading_reminders" edges to the ReadingReminder entity.
func (_u *UserUpdateOne) AddReadingReminders(v ...*ReadingReminder) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReadingReminderIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearBooks clears all "books" edges to the Book entity.
func (_u *UserUpdateOne) ClearBooks() *UserUpdateOne {
	_u.mutation.ClearBooks()
	return _u
}

// RemoveBookIDs removes the "books" edge to Book entities by IDs.
func (_u *UserUpdateOne) RemoveBookIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBooks removes "books" edges to Book entities.
func (_u *UserUpdateOne) RemoveBooks(v ...*Book) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (_u *UserUpdateOne) ClearReviews() *UserUpdateOne {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (_u *UserUpdateOne) RemoveReviewIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to Review entities.
func (_u *UserUpdateOne) RemoveReviews(v ...*Review) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// ClearBookmarks clears all "bookmarks" edges to the Bookmark entity.
func (_u *UserUpdateOne) ClearBookmarks() *UserUpdateOne {
	_u.mutation.ClearBookmarks()
	return _u
}

// RemoveBookmarkIDs removes the "bookmarks" edge to Bookmark entities by IDs.
func (_u *UserUpdateOne) RemoveBookmarkIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveBookmarkIDs(ids...)
	return _u
}

// RemoveBookmarks removes "bookmarks" edges to Bookmark entities.
func (_u *UserUpdateOne) RemoveBookmarks(v ...*Bookmark) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookmarkIDs(ids...)
}

// ClearReadingReminders clears all "reading_reminders" edges to the ReadingReminder entity.
func (_u *UserUpdateOne) ClearReadingReminders() *UserUpdateOne {
	_u.mutation.ClearReadingReminders()
	return _u
}

// RemoveReadingReminderIDs removes the "reading_reminders" edge to ReadingReminder entities by IDs.
func (_u *UserUpdateOne) RemoveReadingReminderIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveReadingReminderIDs(ids...)
	return _u
}

// RemoveReadingReminders removes "reading_reminders" edges to ReadingReminder entities.
func (_u *UserUpdateOne) RemoveReadingReminders(v ...*ReadingReminder) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReadingReminderIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.NickName(); ok {
		if err := user.NickNameValidator(v); err != nil {
			return &ValidationError{Name: "nick_name", err: fmt.Errorf(`ent: validator failed for field "User.nick_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NickName(); ok {
		_spec.SetField(user.FieldNickName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(user.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(user.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsTermsAgreed(); ok {
		_spec.SetField(user.FieldIsTermsAgreed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPrivacyAgreed(); ok {
		_spec.SetField(user.FieldIsPrivacyAgreed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FcmToken(); ok {
		_spec.SetField(user.FieldFcmToken, field.TypeString, value)
	}
	if _u.mutation.FcmTokenCleared() {
		_spec.ClearField(user.FieldFcmToken, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(user.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BooksTable,
			Columns: []string{user.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBooksIDs(); len(nodes) > 0 && !_u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BooksTable,
			Columns: []string{user.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BooksTable,
			Columns: []string{user.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewsTable,
			Columns: []string{user.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewsTable,
			Columns: []string{user.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewsTable,
			Columns: []string{user.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookmarksTable,
			Columns: []string{user.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookmarksIDs(); len(nodes) > 0 && !_u.mutation.BookmarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookmarksTable,
			Columns: []string{user.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookmarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookmarksTable,
			Columns: []string{user.BookmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReadingRemindersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReadingRemindersTable,
			Columns: []string{user.ReadingRemindersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(readingreminder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReadingRemindersIDs(); len(nodes) > 0 && !_u.mutation.ReadingRemindersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReadingRemindersTable,
			Columns: []string{user.ReadingRemindersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(readingreminder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReadingRemindersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReadingRemindersTable,
			Columns: []string{user.ReadingRemindersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(readingreminder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
