// Code generated by ent, DO NOT EDIT.

package readingreminder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/dev-hyunsang/home-library/lib/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldLTE(FieldID, id))
}

// ReminderTime applies equality check predicate on the "reminder_time" field. It's identical to ReminderTimeEQ.
func ReminderTime(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldReminderTime, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldIsEnabled, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldUpdatedAt, v))
}

// ReminderTimeEQ applies the EQ predicate on the "reminder_time" field.
func ReminderTimeEQ(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldReminderTime, v))
}

// ReminderTimeNEQ applies the NEQ predicate on the "reminder_time" field.
func ReminderTimeNEQ(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNEQ(FieldReminderTime, v))
}

// ReminderTimeIn applies the In predicate on the "reminder_time" field.
func ReminderTimeIn(vs ...string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldIn(FieldReminderTime, vs...))
}

// ReminderTimeNotIn applies the NotIn predicate on the "reminder_time" field.
func ReminderTimeNotIn(vs ...string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNotIn(FieldReminderTime, vs...))
}

// ReminderTimeGT applies the GT predicate on the "reminder_time" field.
func ReminderTimeGT(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldGT(FieldReminderTime, v))
}

// ReminderTimeGTE applies the GTE predicate on the "reminder_time" field.
func ReminderTimeGTE(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldGTE(FieldReminderTime, v))
}

// ReminderTimeLT applies the LT predicate on the "reminder_time" field.
func ReminderTimeLT(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldLT(FieldReminderTime, v))
}

// ReminderTimeLTE applies the LTE predicate on the "reminder_time" field.
func ReminderTimeLTE(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldLTE(FieldReminderTime, v))
}

// ReminderTimeContains applies the Contains predicate on the "reminder_time" field.
func ReminderTimeContains(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldContains(FieldReminderTime, v))
}

// ReminderTimeHasPrefix applies the HasPrefix predicate on the "reminder_time" field.
func ReminderTimeHasPrefix(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldHasPrefix(FieldReminderTime, v))
}

// ReminderTimeHasSuffix applies the HasSuffix predicate on the "reminder_time" field.
func ReminderTimeHasSuffix(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldHasSuffix(FieldReminderTime, v))
}

// ReminderTimeEqualFold applies the EqualFold predicate on the "reminder_time" field.
func ReminderTimeEqualFold(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEqualFold(FieldReminderTime, v))
}

// ReminderTimeContainsFold applies the ContainsFold predicate on the "reminder_time" field.
func ReminderTimeContainsFold(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldContainsFold(FieldReminderTime, v))
}

// DayOfWeekEQ applies the EQ predicate on the "day_of_week" field.
func DayOfWeekEQ(v DayOfWeek) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldDayOfWeek, v))
}

// DayOfWeekNEQ applies the NEQ predicate on the "day_of_week" field.
func DayOfWeekNEQ(v DayOfWeek) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNEQ(FieldDayOfWeek, v))
}

// DayOfWeekIn applies the In predicate on the "day_of_week" field.
func DayOfWeekIn(vs ...DayOfWeek) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldIn(FieldDayOfWeek, vs...))
}

// DayOfWeekNotIn applies the NotIn predicate on the "day_of_week" field.
func DayOfWeekNotIn(vs ...DayOfWeek) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNotIn(FieldDayOfWeek, vs...))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNEQ(FieldIsEnabled, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldContainsFold(FieldMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.ReadingReminder {
	return predicate.ReadingReminder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.ReadingReminder {
	return predicate.ReadingReminder(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReadingReminder) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReadingReminder) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReadingReminder) predicate.ReadingReminder {
	return predicate.ReadingReminder(sql.NotPredicates(p))
}
